import Testing
@testable import CtrlKD

/// Ports of the Python `parse_ws` unit tests, plus two cases covering behavior the
/// vector suite provably does not discriminate (see `gapClosing` tests at the bottom —
/// each was mutation-proven necessary, and each expectation was generated by running the
/// real Python `parse_ws`, not derived by hand).

// MARK: - ports of the named Python tests

/// Inline style toggles, typed so the long fixture concatenations below stay cheap for the
/// type-checker (a bare `[0x02]` literal in a chain of `+` sends it exponential).
let boldOn: [UInt8] = [0x02]
let italicOn: [UInt8] = [0x19]

@Test func boldAndParagraphs() {
    // Mirrors test_bold_and_paragraphs.
    var data: [UInt8] = boldOn + ws4Text("Big Title") + boldOn
    data += HARD + HARD
    data += ws4Text("Plain body text follows the heading here.") + HARD
    let doc = parseWS(data)
    let paras = doc.blocks.filter { $0.kind == .para }
    #expect(paras.count == 2)
    #expect(paras[0].lines[0].spans[0].styles.contains(.bold))
    #expect(paras[0].lines[0].text().trimmed() == "Big Title")
    #expect(paras[1].lines[0].spans[0].styles == [])
}

@Test func underlineSpansAndHibitStrip() {
    // Mirrors test_underline_spans_and_hibit_strip.
    let data = ws4Text("I read") + [0x20, 0x13] + ws4Text("A Book") + [0x13] + HARD
    let doc = parseWS(data)
    let spans = doc.blocks[0].lines[0].spans
    let underlined = spans.filter { $0.styles.contains(.underline) }
    #expect(underlined.map(\.text).joined() == "A Book")
    #expect(doc.blocks[0].lines[0].text() == "I read A Book")
}

@Test func ws4HighbitControlToggle() {
    // Mirrors test_ws4_highbit_control_toggle — the landmine: WS4 sets bit 7 on the last
    // char of a word EVEN when it's a style toggle, so 0x94 (= ^T | 0x80) must close the
    // superscript rather than leaking into the text.
    let data = ws4Text("Treaties were made.") + [0x14, 0x31, 0x94, 0x20, 0x20] +
               ws4Text("Officially the era ended there.") + HARD
    let doc = parseWS(data)
    #expect(doc.detection?.variant == .ws4)
    let spans = doc.blocks[0].lines[0].spans
    let sup = spans.filter { $0.styles.contains(.sup) }
    #expect(sup.map(\.text).joined() == "1")
    let tail = spans[spans.count - 1]
    #expect(!tail.styles.contains(.sup))
    #expect(!tail.text.contains("\u{14}"))
}

@Test func dotPABecomesPagebreak() {
    // Mirrors test_dot_pa_becomes_pagebreak.
    let data = bytes("Page one text here.") + HARD + bytes(".pa") + HARD +
               bytes("Page two text here.") + HARD
    let doc = parseWS(data)
    #expect(doc.blocks.map(\.kind) == [.para, .pagebreak, .para])
    #expect(doc.dotCommands == [".pa"])
}

@Test func rulerMarksColumnar() {
    // Mirrors test_ruler_marks_columnar.
    let data = bytes(".rr----!----!----R") + HARD + bytes("Col1    Col2") + HARD
    let doc = parseWS(data)
    #expect(doc.columnar)
}

@Test func ws7FootnoteExtractionAndRef() {
    // Mirrors test_ws7_footnote_extraction_and_ref.
    let data = ws7Block(0x00) + bytes("Treaties were made.") +
               ws7Note(bytes("See the 1868 accords.")) +
               bytes(" More text follows here.") + HARD
    let doc = parseWS(data)
    #expect(doc.detection?.variant == .ws5plus)
    #expect(doc.footnotes.count == 1)
    #expect(doc.footnotes[0].map(\.text).joined() == "See the 1868 accords.")
    let refs = doc.blocks[0].lines[0].spans.filter { $0.styles.contains(.fnref) }
    #expect(refs.count == 1)
    #expect(refs.first?.text == "1")
    #expect(refs.first?.styles.contains(.sup) == true)
}

@Test func ws7HeadingAndSoftpage() {
    // Mirrors test_ws7_heading_and_softpage. Heading level comes from the NAME the style
    // handle resolves to in the document's own library — never from the slot number (the
    // old mapping promoted NOVEL.WS's footer style to a heading while its real H1/H2/H3
    // went unmapped). Slot 2 here resolves to 'H2'.
    let lib = styleLibrary([
        (name: "WordStar Defaults", record: nil),
        (name: "WordStar Defaults", record: nil),
        (name: "H2", record: styleRecord()),
    ])
    let data = documentWithStyleLibrary(
        body: styleRef(2) + bytes("Chapter One") + HARD + HARD
            + bytes("Body text of the chapter.") + HARD
            + ws7Block(0x0B) + bytes("Next page text.") + HARD,
        library: lib)
    let doc = parseWS(data)
    #expect(doc.blocks.first { $0.heading != 0 }?.styleName == "H2")
    #expect(doc.blocks.first { $0.heading != 0 }?.styleID == 2)
    let headings = doc.blocks.filter { $0.heading != 0 }
    #expect(headings.first?.heading == 2)
    #expect(headings.first?.lines[0].text().trimmed() == "Chapter One")
    #expect(doc.blocks.contains { $0.lines.contains(where: \.softpage) })
    // The Python test's last two assertions, which this port had to leave out until the
    // markdown and html emitters existed. Both do now.
    #expect(emitMarkdown(doc).contains("## Chapter One"))
    // The `<h2>` now carries the style's pass-through class, so match around it rather
    // than on the bare tag (Python swapped to a regex here for the same reason).
    let html = emitHTML(doc)
    #expect(html.contains("<h2") && html.contains(">Chapter One</h2>"))
}

@Test func ws7TabBlock() {
    // Mirrors test_ws7_tab_block: a tab block expands to four literal spaces.
    let data = ws7Block(0x00) + ws7Block(0x09) + bytes("Indented by tab block.") + HARD
    let doc = parseWS(data)
    #expect(doc.blocks[0].lines[0].text().hasPrefix("    "))
}

// MARK: - extended-character escape: pins the parse layer, guards against a wrong fix

/// A public-archive WordStar document surfaced a control-byte leak into converted
/// output (two `0x1C` in one file, one `0x1E` in another — both via `-t html`, near a
/// WS5+ heading built from a paragraph-style symmetric block). Root-cause tracing
/// (byte-identical `symmetricBlocks` output confirmed against the real Python
/// reference, then a line-by-line replay of `_decode_spans`/`decodeSpans`) found the
/// defect is NOT in either parser: both implementations' extended-character escape
/// (`0x1B` + the following byte, meant to smuggle a HIGH byte past WS4's bit-7
/// stripping — core.py:186-187) append that following byte completely
/// unconditionally, low control bytes included, and Python's raw parsed `Document`
/// carries the exact same leaked byte Swift's does — verified directly against
/// `ctrl-kd` 1.2.0's own `parse_ws`, not assumed.
///
/// Python's CLI output looks clean anyway, but only for SOME formats, and only by
/// accident: `str.isspace()`/`.strip()`/`.lstrip()` treat 0x1C-0x1F (the ASCII
/// information separators) as whitespace, so wherever an emit-layer function trims
/// whitespace at a text/token boundary (`emit.py`'s heading `.strip()`, its "typescript
/// indent" `.lstrip()`, `pdf.py`'s `_wrap_line` trailing-token pop), it silently
/// absorbs the leaked byte — while `text`/`rtf` output, which never trims that content
/// at all, still shows it raw on BOTH sides (confirmed: neither implementation's parse
/// layer discards it, so there is nothing to fix there for those two formats).
///
/// This makes the escape genuinely NOT a bug to close in this file: converting the
/// escaped byte here (tried, then reverted after it broke `text`/`rtf`/`pdf`, which
/// matched Python before the attempt) changes the SAME span text for every format at
/// once, but Python's apparent behavior is format-specific — some of its emit
/// functions classify 0x1C-0x1F as whitespace and trim them away, some don't. Matching
/// that from a single shared `Document` requires the trim functions themselves to use
/// Python's wider whitespace definition, which is `Sources/CtrlKD/Whitespace.swift`'s
/// `pythonWhitespace` set (`PDFLayout.swift`'s `isSpaceRun` has the same gap for the
/// PDF wrap path) — both outside this fix's owned files (`SymmetricBlocks.swift`,
/// `ParseWS.swift`). See the report for the exact two-line/one-set patch verified
/// (then reverted, since neither file is owned here) to close every remaining
/// difference between the two archive files across all five formats.
///
/// This test pins the CORRECT (already Python-matching) parse-level behavior so a
/// future change here doesn't "fix" it again by mistake and regress `text`/`rtf`/`pdf`
/// the way the first attempt did.
/// UPDATED 2026-08-04, with Python (the same test moved there in the same commit): the
/// escaped byte survives as its cp437 GLYPH (☺∟↔▲▼), not as the raw control. WSFORMAT is
/// explicit that the wrapped byte is "a character to display", and for 00h-1Fh/7Fh that
/// display is IBM's graphics set, never the control ACTION — ASCIITAB.WS wraps every
/// control code precisely to PRINT that chart, and emitting the raw byte put literal tabs
/// and CRs inside its table rows. Nothing is swallowed either way, which is what the
/// investigation above was pinning; the leak it describes is now decoded instead of
/// depending on an emitter to trim it.
@Test func extendedEscapeRendersControlBytesAsTheirCP437Glyphs() {
    for byte: UInt8 in [0x01, 0x1C, 0x1D, 0x1E, 0x1F] {
        let data = bytes("A") + [0x1B, byte] + bytes("B") + HARD
        let text = parseWS(data).blocks[0].lines[0].text()
        let expected = "A" + cp437Graphics[byte]! + "B"
        #expect(text == expected, "escaped 0x\(String(byte, radix: 16)) must render as its cp437 glyph, matching Python")
    }
}

/// Regression guard for the escape's actual documented purpose — smuggling a HIGH
/// byte (an extended cp437 character) past WS4's bit-7 stripping — using the same
/// shape as the real Python vector this project ships (job-006 `parse_ws[5]`,
/// `input_hex` `...1b8220 6f6b2e...`): `0x1B 0x82` decodes to 'é'. Confirms the escape
/// path above is untouched for the byte range it actually exists to serve.
@Test func extendedEscapeStillSmugglesHighByteAsExtendedCharacter() {
    let data = bytes("here ") + [0x1B, 0x82] + bytes(" ok.") + HARD
    #expect(parseWS(data).blocks[0].lines[0].text() == "here \u{e9} ok.")
}

// MARK: - `<1B x 1C>` triples are opaque units; a bare 0x1D is not a block
//
// All five tests below come from ONE file: ASCIITAB.WS, the archive's own cp437 chart,
// every cell of which is a wrapped character. It converted to 266 characters from 4096
// bytes. Expectations were generated by running the real Python `parse_ws`, not derived
// by hand.

@Test func aWrappedByteNeverStartsASymmetricBlock() {
    // The chart's `<1B 1D 1C>` cell read as a block start whose overrunning "jump" (the
    // next two chart bytes) swallowed 3.5 KB to end of file. The walker consumes `<1B x>`
    // escape pairs BEFORE it looks for a 0x1D, so the wrapped byte is data, and both
    // bytes travel on to `decodeSpans`.
    let wrappedGS: [UInt8] = [0x1B, 0x1D, 0x1C]
    let data = ws7Block(0x00) + bytes("cell ") + wrappedGS + bytes(" after") + HARD
        + bytes("A second paragraph survives.") + HARD
    #expect(detect(data).variant == .ws5plus)         // the block walker really did run
    let doc = parseWS(data)
    #expect(doc.blocks[0].lines.map { $0.text() }
            == ["cell ↔ after", "A second paragraph survives."])
}

@Test func aWrappedControlByteIsAGlyphNotTheControlAction() {
    // WSFORMAT: the middle byte is "a character to display", for any value 00h-FFh. For
    // 00h-1Fh/7Fh that display is IBM's cp437 GRAPHICS — the chart exists to print them —
    // and emitting the raw byte instead put literal tabs and CRs inside its table rows.
    let doc = parseWS(ws7Block(0x00) + bytes("Row A ")
                      + [0x1B, 0x0D, 0x1C] + [0x1B, 0x0A, 0x1C] + bytes(" one line.") + HARD)
    #expect(doc.blocks[0].lines.map { $0.text() } == ["Row A ♪◙ one line."])
}

@Test func aWrappedEOFByteDoesNotCutTheDocument() {
    // `<1B 1A 1C>` is the chart's 1A cell. Cutting there amputated 86% of the file.
    // built up in stages: chonky's Swift 6.2.4 type-checker times out on the
    // one-expression form that 6.3.3 accepts (found by the first worker build)
    var data = ws7Block(0x00) + bytes("Chart row ")
    data += [0x1B, 0x1A, 0x1C]
    data += bytes(" continues.") + HARD
    data += bytes("And the file is not cut here.") + HARD
    let doc = parseWS(data)
    #expect(doc.blocks[0].lines.map { $0.text() }
            == ["Chart row → continues.", "And the file is not cut here."])
}

@Test func aWrappedFormFeedIsAGlyphNotAPageEject() {
    // The bare-form-feed split has to skip triple middles for the same reason the line
    // tokenizer does — otherwise the 0C cell ejects a page in the middle of a table row.
    let doc = parseWS(ws7Block(0x00) + bytes("Cell ") + [0x1B, 0x0C, 0x1C]
                      + bytes(" no eject.") + HARD)
    #expect(!doc.blocks.contains { $0.kind == .pagebreak })
    #expect(doc.blocks[0].lines.map { $0.text() } == ["Cell ♀ no eject."])

    // A BARE 0x0C still ejects: the rule is "not a triple middle", not "never".
    let bare = parseWS(ws7Block(0x00) + bytes("top") + [0x0C] + bytes("bottom") + HARD)
    #expect(bare.blocks.map(\.kind) == [.para, .pagebreak, .para])
}

@Test func aWrappedFormFeedOnALineWithAStyleMarkDoesNotSplitTheBlock() {
    // The form-feed branch decodes EVERY part of the line, the trailing one included,
    // and leaves `raw` empty (core.py's `raw = b''`). Keeping the last part back and
    // decoding it after the structural-mark loop instead puts a paragraph-style
    // selection's `closeBlock()` BEFORE content Python had already filled in, and the
    // document gains a block boundary Python does not have.
    //
    // The shape is a real one: a two-column crib table whose rows carry a wrapped control
    // glyph and end with a style selection back to body copy. Expectations generated by
    // running the real Python `parse_ws` on the identical bytes — the 0x0B row (no 0x0C
    // anywhere, so the branch never runs) and the 0x0C row must land in the SAME block.
    let lib = styleLibrary([
        (name: "WordStar Defaults", record: nil),
        (name: "Body copy", record: styleRecord()),
        (name: "Crib label", record: styleRecord(left: 900, just: 2)),
    ])
    let tab = ws7Block(0x09, payload: le16(900) + le16(900) + [0x20, 0x05])
    let wrapped0B: [UInt8] = [0x1B, 0x0B, 0x1C]
    let wrapped0C: [UInt8] = [0x1B, 0x0C, 0x1C]
    let body = styleRef(1)
        + bytes("A prose paragraph long enough to set the wrap margin honestly.") + HARD
        + tab + styleRef(2) + bytes("11") + tab + wrapped0B + bytes(" ") + wrapped0B
        + styleRef(1) + HARD
        + tab + styleRef(2) + bytes("12") + tab + wrapped0C + bytes(" ") + wrapped0C
        + styleRef(1) + HARD
        + bytes("Closing prose after the crib table.") + HARD
    let doc = parseWS(documentWithStyleLibrary(body: body, library: lib))
    #expect(!doc.blocks.contains { $0.kind == .pagebreak })
    #expect(doc.blocks.map(\.styleName) == ["Body copy", "Crib label", "Body copy"])
    #expect(doc.blocks[1].lines.map { $0.text() } == ["     11     ♂ ♂", "     12     ♀ ♀"])
}

@Test func theFlaggedControlMaskSkipsWrappedCharacters() {
    // The ws5+ flagged-control allowlist maps 0x8C -> 0x0C (form feed) and 0x82 -> 0x02
    // (bold toggle). Applied to a triple's MIDDLE byte it would turn a wrapped character
    // into structure or a style toggle, so it runs segment-wise outside triples —
    // length-preservingly, so recorded offsets (marks, tabAt) stay valid.
    let ff = parseWS(ws7Block(0x00) + bytes("A wrapped form feed ") + [0x1B, 0x8C, 0x1C]
                     + bytes(" is a glyph, not a page eject.") + HARD)
    #expect(!ff.blocks.contains { $0.kind == .pagebreak })
    #expect(ff.blocks[0].lines[0].text() == "A wrapped form feed î is a glyph, not a page eject.")

    let bold = parseWS(ws7Block(0x00) + bytes("A wrapped ") + [0x1B, 0x82, 0x1C]
                       + bytes(" stays plain text.") + HARD)
    #expect(bold.blocks[0].lines[0].text() == "A wrapped é stays plain text.")
    #expect(bold.blocks[0].lines[0].spans.allSatisfy { !$0.styles.contains(.bold) })
}

/// Regression guard: bare (non-escaped) 0x1E/0x1F keep their deliberate soft-hyphen
/// meaning — 0x1E dropped entirely, 0x1F rendered as a literal hyphen — confirming the
/// investigation above never touched this branch.
@Test func nonEscapedSoftHyphensKeepTheirDeliberateMeaning() {
    let inactive = bytes("wave") + [0x1E] + bytes("length") + HARD
    #expect(parseWS(inactive).blocks[0].lines[0].text() == "wavelength")

    let active = bytes("wave") + [0x1F] + bytes("length") + HARD
    #expect(parseWS(active).blocks[0].lines[0].text() == "wave-length")
}

// MARK: - gap-closing tests (mutation-proven necessary; not covered by the vectors)

@Test func ws4StrayGroupSeparatorIsNotBlockSyntax() {
    // No ws4 vector contains a 0x1D byte, so removing parseWS's ws5+ gate — letting
    // symmetricBlocks run on a ws4 document — passes the whole vector suite. It must not:
    // in a ws4 file a 0x1D is ordinary control noise that decodeSpans drops (counting it
    // into unknownCodes), NOT a symmetric-block marker whose "length" would eat the
    // following text. Expectation from the real Python parse_ws on this input.
    let data = ws4Text("Stray block marker") + [0x1d] + ws4Text("follows inline here") + HARD
    let doc = parseWS(data)
    #expect(doc.detection?.variant == .ws4)
    #expect(doc.blocks.count == 1)
    #expect(doc.blocks[0].lines[0].text() == "Stray block markerfollows inline here")
    #expect(doc.unknownCodes == [0x1d: 1])
}

@Test func wrapJoinSpaceInheritsClosedSpanStyles() {
    // ctrl-kd 2.0.0: `block.lines` is now PHYSICAL, so the join space this test proves is
    // no longer inserted at parse time — that logic moved to `mergedLines` (Block.swift),
    // which this test now calls directly, matching Python's own `parse_ws`/
    // `core.merged_lines` split. The vectors' only wrap-join space has empty styles, so
    // swapping `last.styles` for the live `active` set passes the whole suite. Here bold
    // OPENS and CLOSES on the first line, so at the wrap point `active` is empty but the
    // last span is still bold — Python gives the join space the span's styles, so it is
    // bold while the continuation text is not. Expectation from the real Python parse_ws.
    let longLine = ws4Text(String(repeating: "x", count: 50) +
                           " words continue flowing here toward margin")
    var data: [UInt8] = boldOn + longLine + boldOn
    data += SOFT + ws4Text("and wrap onto this line.") + HARD
    let doc = parseWS(data)
    #expect(doc.marginEstimate == 92)
    #expect(doc.blocks[0].lines[0].soft == true, "the wrapped physical line must be marked soft")
    let spans = mergedLines(doc.blocks[0])[0].spans
    #expect(spans.count == 3)
    #expect(spans[1].text == " ")
    #expect(spans[1].styles == .bold)      // the join space, inherited from the closed span
    #expect(spans[2].styles == [])         // the continuation, after bold closed
}

/// A dot command from a damaged file can carry an arbitrarily long numeral, and
/// `Double("999...9")` returns +infinity rather than failing. That reached the page
/// geometry and trapped in `Int(x)` during printed-PDF layout — a crash on a file the
/// parser had accepted. Non-finite values are now rejected so the caller's default wins.
@Test func absurdlyLongDotCommandNumberIsRejectedNotInfinite() throws {
    let data = Array(".PL ".utf8) + Array(repeating: UInt8(ascii: "9"), count: 400)
        + [0x0D, 0x0A] + Array("Body.".utf8) + [0x0D, 0x0A]
    let doc = parseWS(data)
    // The absurd value must not have become the page geometry.
    if let h = doc.page?.heightIn { #expect(h.isFinite, "page height went non-finite") }
    #expect(doc.page?.sizeSource == .default, "a damaged .pl must fall back to the default")
}

@Test func realControlCodesAreNotMistakenForStructure() {
    // The sentinels were IN-BAND BYTES, and every byte available for one is a real
    // WordStar control code:
    //
    //     SENT_FNREF    0x00 = ^@ fix print position   (2328 in 5 archive docs)
    //     SENT_SOFTPAGE 0x0B = ^K index marker         (21 in 3)
    //     SENT_HEADING  0x11 = ^Q custom print control (37 in 5)
    //
    // A literal ^K produced a page break the author never wrote. Marks now travel as
    // OFFSETS — the pattern `tabAt` already used, and whose own comment said "that
    // lesson is cheap to apply here". It had not been applied backwards until now.
    for byte: UInt8 in [0x00, 0x0B, 0x11] {
        let doc = parseWS(wsBlock(cmd: 0x00)
                          + bytes("Ordinary prose here, plenty of it. ")
                          + [byte] + bytes("More prose follows on.\r\n"))
        #expect(doc.blocks.map(\.kind) == [.para], "\(byte) invented a block")
        #expect(doc.blocks[0].heading == 0, "\(byte) invented a heading")
        #expect(!doc.blocks.contains { $0.lines.contains { $0.spans.contains {
            $0.styles.contains(.fnref) } } }, "\(byte) invented a note reference")
    }
}

@Test func aLiteralFormFeedBreaksThePageInAWSDocument() {
    // WSFORMAT.TXT: "0Ch ^L  Form Feed.  At print time causes page to be ejected."
    // `parsePrintstream` honoured it; `parseWS` did not, so a WS document carrying ^L
    // ran its two pages together into ONE paragraph, the only trace an "unknown code"
    // line. The two parse paths disagreed about identical bytes.
    let src = bytes("Page one text here with plenty of ordinary prose.")
        + [0x0C] + bytes("Page two text here also with prose.\r\n")
    let doc = parseWS(src)
    #expect(doc.blocks.map(\.kind) == [.para, .pagebreak, .para])
    #expect(doc.unknownCodes.isEmpty, "a handled code must not be reported unknown")
    #expect(parsePrintstream(src).blocks.map(\.kind) == doc.blocks.map(\.kind))

    // EVERY bare form feed ejects, the one that OPENS the document included. This port
    // used to guard the eject on something already being open, so a document beginning
    // with ^L — a deliberate blank first page — silently lost it while Python
    // (`if n:` over the split parts, no guard) kept it. Verified against the reference.
    let leading = parseWS(ws7Block(0x00) + [0x0C] + bytes("After the eject.") + HARD)
    #expect(leading.blocks.map(\.kind) == [.pagebreak, .para])
}

// MARK: - The paragraph style library (C1)

@Test func styleLibraryParsesWithThirtyThreeByteStride() {
    // The "garbage entries" were a wrongly assumed 32-byte index stride; the spec's own
    // field list sums to 24+1+2+2+4 = 33. With stride 33, corpus validation decodes
    // 194/194 index entries and 59/59 style records across every document carrying a
    // library, zero errors.
    let lib = styleLibrary([
        (name: "WordStar Defaults", record: nil),
        (name: "WordStar Defaults", record: nil),
        (name: nil, record: nil),                                 // deleted slot: skipped
        (name: "MS Body Copy", record: styleRecord(just: 0)),
        (name: "Old Tabs", record: styleRecord(inheritTabs: true)),
    ])
    let doc = parseWS(documentWithStyleLibrary(
        body: bytes("Some body text follows.") + HARD, library: lib))
    #expect(doc.styles.map(\.name) == ["WordStar Defaults", "WordStar Defaults",
                                       "MS Body Copy", "Old Tabs"])
    let bodyStyle = try! #require(doc.styles[2].record)
    #expect(bodyStyle.leftMarginHMI == 1800)
    #expect(bodyStyle.rightMarginHMI == nil)                      // -2 sentinel
    #expect(bodyStyle.tabsHMI == [900, 1800])
    // Spec byte 0 is "no justification", which is this parser's `.left`; byte 1 ("right
    // justified") is WordStar-speak for FULL justification, and -3 ("flush right") is
    // what today reads as right-aligned.
    #expect(bodyStyle.justification == .left)
    #expect(bodyStyle.attrsOn == 0b1000000)
    #expect(bodyStyle.lineSpacing == nil)
    // tab counts 0xFF mean INHERITED and the array is stale — never read it
    #expect(doc.styles[3].record?.tabsHMI == nil)
    // and the recordless base entry is a real, selectable style that simply carries none
    #expect(doc.styles[0].record == nil)
}

@Test func styleLibraryPointerAtEOFMeansNoLibrary() {
    // 56 of 85 corpus documents: pointer == file length, WordStar's "next available
    // offset" default when no style was ever defined. Not an error.
    var data = ws7Block(0x00, payload: [0x70] + [UInt8](repeating: 0, count: 15))
        + bytes("Text.") + HARD
    let length = data.count
    for k in 0..<4 { data[4 + 12 + k] = UInt8((length >> (8 * k)) & 0xFF) }
    #expect(parseWS(data).styles.isEmpty)
}

@Test func styleRecordFormattingAppliesAndPersists() {
    // A 0x11 selection applies its record's formatting from that paragraph ON, until the
    // next selection (real documents switch back explicitly — NOVEL.WS re-selects 'MS
    // Body Copy' after every heading). Inherited fields fall back to the running
    // dot-command state; selecting the recordless base entry resets everything.
    let rec = styleRecord(left: 900, just: -2, attrsOn: 0x40)   // centered, lm 5 cols, bold
    let lib = styleLibrary([
        (name: "WordStar Defaults", record: nil),
        (name: "WordStar Defaults", record: nil),
        (name: "Callout", record: rec),
    ])
    let doc = parseWS(documentWithStyleLibrary(
        body: bytes("Plain opening paragraph.") + HARD
            + styleRef(2) + bytes("Styled paragraph one.") + HARD
            + bytes("Still styled, no new selection.") + HARD
            + styleRef(1) + bytes("Back to defaults.") + HARD,
        library: lib))
    // consecutive hard-return lines share a block, so the two styled lines arrive as ONE
    // two-line block — persistence shows in its second line
    #expect(doc.blocks.map { $0.lines[0].text() }
            == ["Plain opening paragraph.", "Styled paragraph one.", "Back to defaults."])
    let (plain, styled, reset) = (doc.blocks[0], doc.blocks[1], doc.blocks[2])
    #expect(styled.lines.map { $0.text() }
            == ["Styled paragraph one.", "Still styled, no new selection."])
    #expect(plain.align == .left && plain.styleAttrs == [])
    #expect(styled.styleName == "Callout")
    #expect(styled.align == .center)
    #expect(styled.leftMargin == 5)                  // 900 HMI / 180
    #expect(styled.rightMargin == nil)               // -2 sentinel: inherited
    #expect(styled.styleAttrs == .bold)
    #expect(reset.styleName == "WordStar Defaults")  // recordless base entry
    #expect(reset.align == .left && reset.styleAttrs == [])
    // the PDF path merges style attrs into every span, like heading bold
    let segments = docToPagelines(doc, printed: false).flatMap { $0 }.flatMap { $0 }
    #expect(segments.contains { $0.text == "Styled" && $0.styles.contains(.bold) })
    #expect(segments.contains { $0.text == "Plain" && !$0.styles.contains(.bold) })
}

@Test func flaggedControlBytesAreControlsNotCP437Glyphs() {
    // MEASURED on WordStar 7 (2026-08-04): a real document's bare 0x8A (flagged ^J)
    // performed a line advance in the printed PCL — zero glyphs — and an injected 0x94
    // (flagged ^T) toggled superscript with a visible font-size/baseline change. Real
    // extended characters travel as <1B xx 1C> triples. Decoding these bytes as cp437
    // invented an e-grave at 14 page boundaries of one document.
    let data = ws7Block(0x00)
        + bytes("the dirt underfoot") + [0x8D, 0x8A] + bytes("ash gray.") + HARD   // WS7's soft pair
        + bytes("wa") + [0x94] + bytes("s") + [0x94] + bytes(" raised text here.") + HARD
    let doc = parseWS(data)
    let txt = emitText(doc, mode: .printed)
    #expect(!txt.contains("è") && !txt.contains("ö"))
    #expect(txt.contains("underfoot") && txt.contains("ash gray."))
    let spans = doc.blocks.flatMap(\.lines).flatMap(\.spans)
    #expect(spans.filter { $0.styles.contains(.sup) }.map(\.text) == ["s"])   // ^T…^T span
    // (wrap-vs-line classification of the soft pair is the margin heuristic's call, same
    // as any 0x8D return — not asserted here)
}

@Test func theFlaggedControlMaskIsAnAllowlistNeverARange() {
    // A blanket 0x80-0x9F mask CREATES structural bytes: 0x9A becomes 0x1A and
    // `linesPass` truncated a whole novel at its first occurrence; 0x9D would become
    // 0x1D block framing. Both bytes must survive the mask untouched, and the text after
    // them must survive with them.
    let doc = parseWS(ws7Block(0x00)
                      + bytes("Before the byte ") + [0x9A]
                      + bytes(" and after it the document continues normally.") + HARD
                      + bytes("A second paragraph proves nothing was truncated.") + HARD)
    let txt = emitText(doc, mode: .printed)
    #expect(txt.contains("A second paragraph proves nothing was truncated."))
}
