import Testing
@testable import CtrlKD

/// Ports of the Python `parse_ws` unit tests, plus two cases covering behavior the
/// vector suite provably does not discriminate (see `gapClosing` tests at the bottom —
/// each was mutation-proven necessary, and each expectation was generated by running the
/// real Python `parse_ws`, not derived by hand).

// MARK: - ports of the named Python tests

/// Inline style toggles, typed so the long fixture concatenations below stay cheap for the
/// type-checker (a bare `[0x02]` literal in a chain of `+` sends it exponential).
let boldOn: [UInt8] = [0x02]
let italicOn: [UInt8] = [0x19]

@Test func boldAndParagraphs() {
    // Mirrors test_bold_and_paragraphs.
    var data: [UInt8] = boldOn + ws4Text("Big Title") + boldOn
    data += HARD + HARD
    data += ws4Text("Plain body text follows the heading here.") + HARD
    let doc = parseWS(data)
    let paras = doc.blocks.filter { $0.kind == .para }
    #expect(paras.count == 2)
    #expect(paras[0].lines[0].spans[0].styles.contains(.bold))
    #expect(paras[0].lines[0].text().trimmed() == "Big Title")
    #expect(paras[1].lines[0].spans[0].styles == [])
}

@Test func underlineSpansAndHibitStrip() {
    // Mirrors test_underline_spans_and_hibit_strip.
    let data = ws4Text("I read") + [0x20, 0x13] + ws4Text("A Book") + [0x13] + HARD
    let doc = parseWS(data)
    let spans = doc.blocks[0].lines[0].spans
    let underlined = spans.filter { $0.styles.contains(.underline) }
    #expect(underlined.map(\.text).joined() == "A Book")
    #expect(doc.blocks[0].lines[0].text() == "I read A Book")
}

@Test func ws4HighbitControlToggle() {
    // Mirrors test_ws4_highbit_control_toggle — the landmine: WS4 sets bit 7 on the last
    // char of a word EVEN when it's a style toggle, so 0x94 (= ^T | 0x80) must close the
    // superscript rather than leaking into the text.
    let data = ws4Text("Treaties were made.") + [0x14, 0x31, 0x94, 0x20, 0x20] +
               ws4Text("Officially the era ended there.") + HARD
    let doc = parseWS(data)
    #expect(doc.detection?.variant == .ws4)
    let spans = doc.blocks[0].lines[0].spans
    let sup = spans.filter { $0.styles.contains(.sup) }
    #expect(sup.map(\.text).joined() == "1")
    let tail = spans[spans.count - 1]
    #expect(!tail.styles.contains(.sup))
    #expect(!tail.text.contains("\u{14}"))
}

@Test func dotPABecomesPagebreak() {
    // Mirrors test_dot_pa_becomes_pagebreak.
    let data = bytes("Page one text here.") + HARD + bytes(".pa") + HARD +
               bytes("Page two text here.") + HARD
    let doc = parseWS(data)
    #expect(doc.blocks.map(\.kind) == [.para, .pagebreak, .para])
    #expect(doc.dotCommands == [".pa"])
}

@Test func rulerMarksColumnar() {
    // Mirrors test_ruler_marks_columnar.
    let data = bytes(".rr----!----!----R") + HARD + bytes("Col1    Col2") + HARD
    let doc = parseWS(data)
    #expect(doc.columnar)
}

@Test func ws7FootnoteExtractionAndRef() {
    // Mirrors test_ws7_footnote_extraction_and_ref.
    let data = ws7Block(0x00) + bytes("Treaties were made.") +
               ws7Note(bytes("See the 1868 accords.")) +
               bytes(" More text follows here.") + HARD
    let doc = parseWS(data)
    #expect(doc.detection?.variant == .ws5plus)
    #expect(doc.footnotes.count == 1)
    #expect(doc.footnotes[0].map(\.text).joined() == "See the 1868 accords.")
    let refs = doc.blocks[0].lines[0].spans.filter { $0.styles.contains(.fnref) }
    #expect(refs.count == 1)
    #expect(refs.first?.text == "1")
    #expect(refs.first?.styles.contains(.sup) == true)
}

@Test func ws7HeadingAndSoftpage() {
    // Mirrors test_ws7_heading_and_softpage.
    let data = ws7Block(0x00) + ws7Block(0x11, payload: [0x02]) + bytes("Chapter One") +
               HARD + HARD + bytes("Body text of the chapter.") + HARD +
               ws7Block(0x0B) + bytes("Next page text.") + HARD
    let doc = parseWS(data)
    let headings = doc.blocks.filter { $0.heading != 0 }
    #expect(headings.first?.heading == 2)
    #expect(headings.first?.lines[0].text().trimmed() == "Chapter One")
    #expect(doc.blocks.contains { $0.kind == .softpage })
    // The Python test's last two assertions, which this port had to leave out until the
    // markdown and html emitters existed. Both do now.
    #expect(emitMarkdown(doc).contains("## Chapter One"))
    #expect(emitHTML(doc).contains("<h2>Chapter One</h2>"))
}

@Test func ws7TabBlock() {
    // Mirrors test_ws7_tab_block: a tab block expands to four literal spaces.
    let data = ws7Block(0x00) + ws7Block(0x09) + bytes("Indented by tab block.") + HARD
    let doc = parseWS(data)
    #expect(doc.blocks[0].lines[0].text().hasPrefix("    "))
}

// MARK: - extended-character escape: pins the parse layer, guards against a wrong fix

/// A public-archive WordStar document surfaced a control-byte leak into converted
/// output (two `0x1C` in one file, one `0x1E` in another — both via `-t html`, near a
/// WS5+ heading built from a paragraph-style symmetric block). Root-cause tracing
/// (byte-identical `symmetricBlocks` output confirmed against the real Python
/// reference, then a line-by-line replay of `_decode_spans`/`decodeSpans`) found the
/// defect is NOT in either parser: both implementations' extended-character escape
/// (`0x1B` + the following byte, meant to smuggle a HIGH byte past WS4's bit-7
/// stripping — core.py:186-187) append that following byte completely
/// unconditionally, low control bytes included, and Python's raw parsed `Document`
/// carries the exact same leaked byte Swift's does — verified directly against
/// `ctrl-kd` 1.2.0's own `parse_ws`, not assumed.
///
/// Python's CLI output looks clean anyway, but only for SOME formats, and only by
/// accident: `str.isspace()`/`.strip()`/`.lstrip()` treat 0x1C-0x1F (the ASCII
/// information separators) as whitespace, so wherever an emit-layer function trims
/// whitespace at a text/token boundary (`emit.py`'s heading `.strip()`, its "typescript
/// indent" `.lstrip()`, `pdf.py`'s `_wrap_line` trailing-token pop), it silently
/// absorbs the leaked byte — while `text`/`rtf` output, which never trims that content
/// at all, still shows it raw on BOTH sides (confirmed: neither implementation's parse
/// layer discards it, so there is nothing to fix there for those two formats).
///
/// This makes the escape genuinely NOT a bug to close in this file: converting the
/// escaped byte here (tried, then reverted after it broke `text`/`rtf`/`pdf`, which
/// matched Python before the attempt) changes the SAME span text for every format at
/// once, but Python's apparent behavior is format-specific — some of its emit
/// functions classify 0x1C-0x1F as whitespace and trim them away, some don't. Matching
/// that from a single shared `Document` requires the trim functions themselves to use
/// Python's wider whitespace definition, which is `Sources/CtrlKD/Whitespace.swift`'s
/// `pythonWhitespace` set (`PDFLayout.swift`'s `isSpaceRun` has the same gap for the
/// PDF wrap path) — both outside this fix's owned files (`SymmetricBlocks.swift`,
/// `ParseWS.swift`). See the report for the exact two-line/one-set patch verified
/// (then reverted, since neither file is owned here) to close every remaining
/// difference between the two archive files across all five formats.
///
/// This test pins the CORRECT (already Python-matching) parse-level behavior so a
/// future change here doesn't "fix" it again by mistake and regress `text`/`rtf`/`pdf`
/// the way the first attempt did.
@Test func extendedEscapePassesLowControlBytesThroughUnfilteredLikePython() {
    for byte: UInt8 in [0x01, 0x1C, 0x1D, 0x1E, 0x1F] {
        let data = bytes("A") + [0x1B, byte] + bytes("B") + HARD
        let text = parseWS(data).blocks[0].lines[0].text()
        let expected = "A" + String(UnicodeScalar(byte)) + "B"
        #expect(text == expected, "escaped 0x\(String(byte, radix: 16)) must pass through raw, matching Python")
    }
}

/// Regression guard for the escape's actual documented purpose — smuggling a HIGH
/// byte (an extended cp437 character) past WS4's bit-7 stripping — using the same
/// shape as the real Python vector this project ships (job-006 `parse_ws[5]`,
/// `input_hex` `...1b8220 6f6b2e...`): `0x1B 0x82` decodes to 'é'. Confirms the escape
/// path above is untouched for the byte range it actually exists to serve.
@Test func extendedEscapeStillSmugglesHighByteAsExtendedCharacter() {
    let data = bytes("here ") + [0x1B, 0x82] + bytes(" ok.") + HARD
    #expect(parseWS(data).blocks[0].lines[0].text() == "here \u{e9} ok.")
}

/// Regression guard: bare (non-escaped) 0x1E/0x1F keep their deliberate soft-hyphen
/// meaning — 0x1E dropped entirely, 0x1F rendered as a literal hyphen — confirming the
/// investigation above never touched this branch.
@Test func nonEscapedSoftHyphensKeepTheirDeliberateMeaning() {
    let inactive = bytes("wave") + [0x1E] + bytes("length") + HARD
    #expect(parseWS(inactive).blocks[0].lines[0].text() == "wavelength")

    let active = bytes("wave") + [0x1F] + bytes("length") + HARD
    #expect(parseWS(active).blocks[0].lines[0].text() == "wave-length")
}

// MARK: - gap-closing tests (mutation-proven necessary; not covered by the vectors)

@Test func ws4StrayGroupSeparatorIsNotBlockSyntax() {
    // No ws4 vector contains a 0x1D byte, so removing parseWS's ws5+ gate — letting
    // symmetricBlocks run on a ws4 document — passes the whole vector suite. It must not:
    // in a ws4 file a 0x1D is ordinary control noise that decodeSpans drops (counting it
    // into unknownCodes), NOT a symmetric-block marker whose "length" would eat the
    // following text. Expectation from the real Python parse_ws on this input.
    let data = ws4Text("Stray block marker") + [0x1d] + ws4Text("follows inline here") + HARD
    let doc = parseWS(data)
    #expect(doc.detection?.variant == .ws4)
    #expect(doc.blocks.count == 1)
    #expect(doc.blocks[0].lines[0].text() == "Stray block markerfollows inline here")
    #expect(doc.unknownCodes == [0x1d: 1])
}

@Test func wrapJoinSpaceInheritsClosedSpanStyles() {
    // ctrl-kd 2.0.0: `block.lines` is now PHYSICAL, so the join space this test proves is
    // no longer inserted at parse time — that logic moved to `mergedLines` (Block.swift),
    // which this test now calls directly, matching Python's own `parse_ws`/
    // `core.merged_lines` split. The vectors' only wrap-join space has empty styles, so
    // swapping `last.styles` for the live `active` set passes the whole suite. Here bold
    // OPENS and CLOSES on the first line, so at the wrap point `active` is empty but the
    // last span is still bold — Python gives the join space the span's styles, so it is
    // bold while the continuation text is not. Expectation from the real Python parse_ws.
    let longLine = ws4Text(String(repeating: "x", count: 50) +
                           " words continue flowing here toward margin")
    var data: [UInt8] = boldOn + longLine + boldOn
    data += SOFT + ws4Text("and wrap onto this line.") + HARD
    let doc = parseWS(data)
    #expect(doc.marginEstimate == 92)
    #expect(doc.blocks[0].lines[0].soft == true, "the wrapped physical line must be marked soft")
    let spans = mergedLines(doc.blocks[0])[0].spans
    #expect(spans.count == 3)
    #expect(spans[1].text == " ")
    #expect(spans[1].styles == .bold)      // the join space, inherited from the closed span
    #expect(spans[2].styles == [])         // the continuation, after bold closed
}

/// A dot command from a damaged file can carry an arbitrarily long numeral, and
/// `Double("999...9")` returns +infinity rather than failing. That reached the page
/// geometry and trapped in `Int(x)` during printed-PDF layout — a crash on a file the
/// parser had accepted. Non-finite values are now rejected so the caller's default wins.
@Test func absurdlyLongDotCommandNumberIsRejectedNotInfinite() throws {
    let data = Array(".PL ".utf8) + Array(repeating: UInt8(ascii: "9"), count: 400)
        + [0x0D, 0x0A] + Array("Body.".utf8) + [0x0D, 0x0A]
    let doc = parseWS(data)
    // The absurd value must not have become the page geometry.
    if let h = doc.page?.heightIn { #expect(h.isFinite, "page height went non-finite") }
    #expect(doc.page?.sizeSource == .default, "a damaged .pl must fall back to the default")
}
