import Testing
@testable import CtrlKD

/// Ports of the Python `parse_ws` unit tests, plus two cases covering behavior the
/// vector suite provably does not discriminate (see `gapClosing` tests at the bottom —
/// each was mutation-proven necessary, and each expectation was generated by running the
/// real Python `parse_ws`, not derived by hand).

// MARK: - ports of the named Python tests

/// Inline style toggles, typed so the long fixture concatenations below stay cheap for the
/// type-checker (a bare `[0x02]` literal in a chain of `+` sends it exponential).
let boldOn: [UInt8] = [0x02]
let italicOn: [UInt8] = [0x19]

@Test func boldAndParagraphs() {
    // Mirrors test_bold_and_paragraphs.
    var data: [UInt8] = boldOn + ws4Text("Big Title") + boldOn
    data += HARD + HARD
    data += ws4Text("Plain body text follows the heading here.") + HARD
    let doc = parseWS(data)
    let paras = doc.blocks.filter { $0.kind == .para }
    #expect(paras.count == 2)
    #expect(paras[0].lines[0].spans[0].styles.contains(.bold))
    #expect(paras[0].lines[0].text().trimmed() == "Big Title")
    #expect(paras[1].lines[0].spans[0].styles == [])
}

@Test func underlineSpansAndHibitStrip() {
    // Mirrors test_underline_spans_and_hibit_strip.
    let data = ws4Text("I read") + [0x20, 0x13] + ws4Text("A Book") + [0x13] + HARD
    let doc = parseWS(data)
    let spans = doc.blocks[0].lines[0].spans
    let underlined = spans.filter { $0.styles.contains(.underline) }
    #expect(underlined.map(\.text).joined() == "A Book")
    #expect(doc.blocks[0].lines[0].text() == "I read A Book")
}

@Test func ws4HighbitControlToggle() {
    // Mirrors test_ws4_highbit_control_toggle — the landmine: WS4 sets bit 7 on the last
    // char of a word EVEN when it's a style toggle, so 0x94 (= ^T | 0x80) must close the
    // superscript rather than leaking into the text.
    let data = ws4Text("Treaties were made.") + [0x14, 0x31, 0x94, 0x20, 0x20] +
               ws4Text("Officially the era ended there.") + HARD
    let doc = parseWS(data)
    #expect(doc.detection?.variant == .ws4)
    let spans = doc.blocks[0].lines[0].spans
    let sup = spans.filter { $0.styles.contains(.sup) }
    #expect(sup.map(\.text).joined() == "1")
    let tail = spans[spans.count - 1]
    #expect(!tail.styles.contains(.sup))
    #expect(!tail.text.contains("\u{14}"))
}

@Test func dotPABecomesPagebreak() {
    // Mirrors test_dot_pa_becomes_pagebreak.
    let data = bytes("Page one text here.") + HARD + bytes(".pa") + HARD +
               bytes("Page two text here.") + HARD
    let doc = parseWS(data)
    #expect(doc.blocks.map(\.kind) == [.para, .pagebreak, .para])
    #expect(doc.dotCommands == [".pa"])
}

@Test func rulerMarksColumnar() {
    // Mirrors test_ruler_marks_columnar.
    let data = bytes(".rr----!----!----R") + HARD + bytes("Col1    Col2") + HARD
    let doc = parseWS(data)
    #expect(doc.columnar)
}

@Test func ws7FootnoteExtractionAndRef() {
    // Mirrors test_ws7_footnote_extraction_and_ref.
    let data = ws7Block(0x00) + bytes("Treaties were made.") +
               ws7Note(bytes("See the 1868 accords.")) +
               bytes(" More text follows here.") + HARD
    let doc = parseWS(data)
    #expect(doc.detection?.variant == .ws5plus)
    #expect(doc.footnotes.count == 1)
    #expect(doc.footnotes[0].map(\.text).joined() == "See the 1868 accords.")
    let refs = doc.blocks[0].lines[0].spans.filter { $0.styles.contains(.fnref) }
    #expect(refs.count == 1)
    #expect(refs.first?.text == "1")
    #expect(refs.first?.styles.contains(.sup) == true)
}

@Test func ws7HeadingAndSoftpage() {
    // Mirrors test_ws7_heading_and_softpage.
    let data = ws7Block(0x00) + ws7Block(0x11, payload: [0x02]) + bytes("Chapter One") +
               HARD + HARD + bytes("Body text of the chapter.") + HARD +
               ws7Block(0x0B) + bytes("Next page text.") + HARD
    let doc = parseWS(data)
    let headings = doc.blocks.filter { $0.heading != 0 }
    #expect(headings.first?.heading == 2)
    #expect(headings.first?.lines[0].text().trimmed() == "Chapter One")
    #expect(doc.blocks.contains { $0.kind == .softpage })
}

@Test func ws7TabBlock() {
    // Mirrors test_ws7_tab_block: a tab block expands to four literal spaces.
    let data = ws7Block(0x00) + ws7Block(0x09) + bytes("Indented by tab block.") + HARD
    let doc = parseWS(data)
    #expect(doc.blocks[0].lines[0].text().hasPrefix("    "))
}

// MARK: - gap-closing tests (mutation-proven necessary; not covered by the vectors)

@Test func ws4StrayGroupSeparatorIsNotBlockSyntax() {
    // No ws4 vector contains a 0x1D byte, so removing parseWS's ws5+ gate — letting
    // symmetricBlocks run on a ws4 document — passes the whole vector suite. It must not:
    // in a ws4 file a 0x1D is ordinary control noise that decodeSpans drops (counting it
    // into unknownCodes), NOT a symmetric-block marker whose "length" would eat the
    // following text. Expectation from the real Python parse_ws on this input.
    let data = ws4Text("Stray block marker") + [0x1d] + ws4Text("follows inline here") + HARD
    let doc = parseWS(data)
    #expect(doc.detection?.variant == .ws4)
    #expect(doc.blocks.count == 1)
    #expect(doc.blocks[0].lines[0].text() == "Stray block markerfollows inline here")
    #expect(doc.unknownCodes == [0x1d: 1])
}

@Test func wrapJoinSpaceInheritsClosedSpanStyles() {
    // The vectors' only wrap-join space has empty styles, so swapping `last.styles` for
    // the live `active` set passes the whole suite. Here bold OPENS and CLOSES on the
    // first line, so at the wrap point `active` is empty but the last span is still
    // bold — Python gives the join space the span's styles, so it is bold while the
    // continuation text is not. Expectation from the real Python parse_ws.
    let longLine = ws4Text(String(repeating: "x", count: 50) +
                           " words continue flowing here toward margin")
    var data: [UInt8] = boldOn + longLine + boldOn
    data += SOFT + ws4Text("and wrap onto this line.") + HARD
    let doc = parseWS(data)
    #expect(doc.marginEstimate == 92)
    let spans = doc.blocks[0].lines[0].spans
    #expect(spans.count == 3)
    #expect(spans[1].text == " ")
    #expect(spans[1].styles == .bold)      // the join space, inherited from the closed span
    #expect(spans[2].styles == [])         // the continuation, after bold closed
}
