import Testing
@testable import CtrlKD

/// The vector suite (`VectorTests.symmetricBlocksMatchesPythonVectors`) proves
/// byte-for-byte equivalence against Athena's 7 machine-generated vectors, but none of
/// those exercise the NBSP-whitespace edge case the job spec called out (space-only
/// strip is not sufficient for `_note_text`). This test closes that gap by hand:
/// expected output was generated by running the real `_symmetric_blocks` in the Python
/// reference on this exact input (see the response for the transcript), not guessed.
@Test func noteTextStripsLeadingTrailingNBSP() {
    // \xff is CP437 for U+00A0 (NBSP), which Python's `str.strip()` removes — unlike a
    // naive space-only trim, which would leave 'Hello there' padded on both sides.
    let data = ws7Block(0x00) + bytes("Body.") +
               ws7Note([0xff] + bytes("Hello there") + [0xff]) +
               bytes(" tail.") + HARD
    let result = symmetricBlocks(data)
    #expect(result.footnotes == ["Hello there"])
    #expect(result.bytes == bytes("Body.") + [SENT_FNREF] + bytes(" tail.") + HARD)
}
