import Foundation
import Testing
@testable import CtrlKD

/// Equivalence proof against `Resources/job-003-vectors.json` — machine-generated by
/// the Python ctrl-kd 1.1.3 implementation. Every vector must reproduce exactly.
///
/// `Foundation` is imported here for `JSONDecoder`/`Bundle` only; the `CtrlKD` library
/// target itself stays Foundation-free.

/// job-008/009/011's `ws5_footnote_heading`/`footnote_doc` vectors were machine-generated
/// (Python 1.1.3/1.1.4) from an `input_hex` that predates ctrl-kd 1.2.0's note-kind fix:
/// its footnote block is laid out in the OLD (spec-incorrect) shape `_note_text` used to
/// read — 17 zero bytes, an inner `0x1D`, the text, a `,\x00` tail — not the real
/// line-count/tag-word/conversion-flag/text layout `parseNote` now decodes (see
/// `SymmetricBlocks.swift`). Verified against the actual Python 1.2.0 reference: fed this
/// same old-shaped input, it recovers empty note text too, not a crash — so this is a
/// stale fixture assumption, not a regression in the (unowned, untouched) emitters/PDF
/// layout these three vectors otherwise exercise. Every other assertion these vectors make
/// remains fully in force; only the footnote-text-bearing name below is skipped, in the
/// three test functions that consume it. Correct extraction from a correctly-shaped block
/// is proven separately by `notesVectors1_2_0` (ground truth from the real, fixed
/// implementation) and `ws7FootnoteExtractionAndRef` (ParseWSTests.swift, using the
/// now-fixed `ws7Note` fixture helper).
private let staleFootnoteVectorNames: Set<String> = [
    "ws5_footnote_heading/text/modern", "ws5_footnote_heading/text/printed",
    "ws5_footnote_heading/markdown/modern", "ws5_footnote_heading/markdown/printed",
    "ws5_footnote_heading/html/modern", "ws5_footnote_heading/html/printed",
    "ws5_footnote_heading/rtf/modern", "ws5_footnote_heading/rtf/printed",
    "footnote_doc/modern", "footnote_doc/printed",
]

/// ctrl-kd 1.2.0 also added two CSS rules to `emit_html`'s style block —
/// `section[role=doc-endnotes]` sizing — and it did so UNCONDITIONALLY: they're present
/// even in a document with no notes at all (confirmed against
/// `notes-vectors-1.2.0.json`'s note-free `geometry_legal`/`wordtsar` cases). Every HTML
/// vector in job-008/009/010 was captured from 1.1.3/1.1.4, before that change, so EVERY
/// one of them is stale in exactly this one place — unlike `staleFootnoteVectorNames`
/// above, this isn't specific to footnote-bearing fixtures; it's a global addition to a
/// part of the page every HTML vector includes. Stripped from the actual output before
/// comparison rather than skipping the vectors outright, so every other byte these
/// vectors pin (style-tag nesting order, escaping, page rules, printed-mode `<pre>`
/// wrapping) stays proven against the old fixtures.
private func strippingNotesCSS(_ html: String) -> String {
    html.replacingOccurrences(
        of: "section[role=doc-endnotes]{margin-top:2rem}\nsection[role=doc-endnotes] h2{font-size:1.1rem}\n",
        with: ""
    )
}

private struct VectorFile: Decodable {
    let detect: [DetectVector]
    let linesPass: [LinesPassVector]
    let note: String

    enum CodingKeys: String, CodingKey {
        case detect
        case linesPass = "lines_pass"
        case note
    }
}

private struct DetectVector: Decodable {
    let inputHex: String
    let variant: String
    // Absent for the empty / ^Z-at-start vectors: Python's detect() returns those before
    // it computes any evidence, so there is nothing to assert for them.
    let softReturns: Int?
    let hardReturns: Int?
    let highBitBytes: Int?
    let textPct: Int?
    let symmetricBlocks1D: Int?
    let size: Int?

    enum CodingKeys: String, CodingKey {
        case inputHex = "input_hex"
        case variant
        case softReturns = "soft_returns"
        case hardReturns = "hard_returns"
        case highBitBytes = "high_bit_bytes"
        case textPct = "text_pct"
        case symmetricBlocks1D = "symmetric_blocks_1d"
        case size
    }
}

private struct LinesPassVector: Decodable {
    let inputHex: String
    let margin: Int
    let lines: [LineVector]

    enum CodingKeys: String, CodingKey {
        case inputHex = "input_hex"
        case margin
        case lines
    }
}

private struct LineVector: Decodable {
    let textHex: String
    let sep: String

    enum CodingKeys: String, CodingKey {
        case textHex = "text_hex"
        case sep
    }
}

private struct Job004VectorFile: Decodable {
    let cp437ByteToUnicodeCodepoint: [String: Int]
    let linesPassExtra: [LinesPassVector]
    let note: String

    enum CodingKeys: String, CodingKey {
        case cp437ByteToUnicodeCodepoint = "cp437_byte_to_unicode_codepoint"
        case linesPassExtra = "lines_pass_extra"
        case note
    }
}

private func loadVectors() throws -> VectorFile {
    let url = try #require(
        Bundle.module.url(forResource: "job-003-vectors", withExtension: "json"),
        "job-003-vectors.json missing from the test bundle"
    )
    return try JSONDecoder().decode(VectorFile.self, from: Data(contentsOf: url))
}

private func loadJob004Vectors() throws -> Job004VectorFile {
    let url = try #require(
        Bundle.module.url(forResource: "job-004-vectors", withExtension: "json"),
        "job-004-vectors.json missing from the test bundle"
    )
    return try JSONDecoder().decode(Job004VectorFile.self, from: Data(contentsOf: url))
}

private struct SymmetricBlocksVector: Decodable {
    let inputHex: String
    let outputHex: String
    let footnotes: [String]

    enum CodingKeys: String, CodingKey {
        case inputHex = "input_hex"
        case outputHex = "output_hex"
        case footnotes
    }
}

private struct Job005VectorFile: Decodable {
    let symmetricBlocks: [SymmetricBlocksVector]
    let note: String

    enum CodingKeys: String, CodingKey {
        case symmetricBlocks = "symmetric_blocks"
        case note
    }
}

private func loadJob005Vectors() throws -> Job005VectorFile {
    let url = try #require(
        Bundle.module.url(forResource: "job-005-vectors", withExtension: "json"),
        "job-005-vectors.json missing from the test bundle"
    )
    return try JSONDecoder().decode(Job005VectorFile.self, from: Data(contentsOf: url))
}

// MARK: - job-006 (parse_ws end-to-end Documents)

private struct SpanVector: Decodable {
    let text: String
    let styles: [String]
}

private struct BlockVector: Decodable {
    let kind: String
    let heading: Int
    /// Python serializes each line as a bare list of spans, so a line is `[[SpanVector]]`
    /// nested one deeper than it reads.
    let lines: [[SpanVector]]
}

private struct MetaVector: Decodable {
    let variant: String
    let marginEstimate: Int
    let dotCommands: [String]
    /// Hex-string keyed (`"0x07"`), matching Python's `--diagnose` formatting; converted
    /// to raw bytes for comparison against `Document.unknownCodes`.
    let unknownCodes: [String: Int]
    let columnar: Bool

    enum CodingKeys: String, CodingKey {
        case variant
        case marginEstimate = "margin_estimate"
        case dotCommands = "dot_commands"
        case unknownCodes = "unknown_codes"
        case columnar
    }
}

private struct DocumentVector: Decodable {
    let blocks: [BlockVector]
    let footnotes: [String]
    let meta: MetaVector
}

private struct ParseWSVector: Decodable {
    let inputHex: String
    let document: DocumentVector

    enum CodingKeys: String, CodingKey {
        case inputHex = "input_hex"
        case document
    }
}

private struct Job006VectorFile: Decodable {
    let parseWS: [ParseWSVector]
    let symmetricBlocksExtra: [SymmetricBlocksVector]
    let note: String

    enum CodingKeys: String, CodingKey {
        case parseWS = "parse_ws"
        case symmetricBlocksExtra = "symmetric_blocks_extra"
        case note
    }
}

private func loadJob006Vectors() throws -> Job006VectorFile {
    let url = try #require(
        Bundle.module.url(forResource: "job-006-vectors", withExtension: "json"),
        "job-006-vectors.json missing from the test bundle"
    )
    return try JSONDecoder().decode(Job006VectorFile.self, from: Data(contentsOf: url))
}

// MARK: - job-007 (parse_printstream + parse front door)

/// Printstream documents carry only `variant` and `columnar` — `parse_printstream` builds
/// its meta by hand and never runs detection or the wrap test.
private struct PrintstreamMetaVector: Decodable {
    let variant: String
    let columnar: Bool
}

private struct PrintstreamDocumentVector: Decodable {
    let blocks: [BlockVector]
    let footnotes: [String]
    let meta: PrintstreamMetaVector
}

private struct PrintstreamVector: Decodable {
    let inputHex: String
    let document: PrintstreamDocumentVector

    enum CodingKeys: String, CodingKey {
        case inputHex = "input_hex"
        case document
    }
}

private struct FrontDoorVector: Decodable {
    let inputHex: String
    let routesTo: String

    enum CodingKeys: String, CodingKey {
        case inputHex = "input_hex"
        case routesTo = "routes_to"
    }
}

private struct Job007VectorFile: Decodable {
    let parsePrintstream: [PrintstreamVector]
    let parseFrontDoor: [FrontDoorVector]
    let note: String

    enum CodingKeys: String, CodingKey {
        case parsePrintstream = "parse_printstream"
        case parseFrontDoor = "parse_front_door"
        case note
    }
}

private func loadJob007Vectors() throws -> Job007VectorFile {
    let url = try #require(
        Bundle.module.url(forResource: "job-007-vectors", withExtension: "json"),
        "job-007-vectors.json missing from the test bundle"
    )
    return try JSONDecoder().decode(Job007VectorFile.self, from: Data(contentsOf: url))
}

// MARK: - job-008 (emitters)

private struct EmitVector: Decodable {
    let name: String
    let inputHex: String
    let format: String
    let mode: String
    let expected: String

    enum CodingKeys: String, CodingKey {
        case name
        case inputHex = "input_hex"
        case format
        case mode
        case expected
    }
}

private struct Job008VectorFile: Decodable {
    let emit: [EmitVector]
    let note: String
}

// MARK: - job-009 (html + rtf emitters)

/// Same shape as `EmitVector` plus the optional `title`, which only the one title-escaping
/// vector carries. Python's `emit_html` defaults it to `''`.
private struct Emit2Vector: Decodable {
    let name: String
    let inputHex: String
    let format: String
    let mode: String
    let expected: String
    let title: String?

    enum CodingKeys: String, CodingKey {
        case name
        case inputHex = "input_hex"
        case format
        case mode
        case expected
        case title
    }
}

private struct Job009VectorFile: Decodable {
    let emit2: [Emit2Vector]
    let note: String
}

private func loadJob009Vectors() throws -> Job009VectorFile {
    let url = try #require(
        Bundle.module.url(forResource: "job-009-vectors", withExtension: "json"),
        "job-009-vectors.json missing from the test bundle"
    )
    return try JSONDecoder().decode(Job009VectorFile.self, from: Data(contentsOf: url))
}

// MARK: - job-010 (convert front door + the form-feed printstream case)

private struct ConvertVector: Decodable {
    let inputHex: String
    let to: String
    let expected: String

    enum CodingKeys: String, CodingKey {
        case inputHex = "input_hex"
        case to
        case expected
    }
}

/// The form-feed emit vectors carry no `name`/`input_hex` of their own — they all render the
/// one document the enclosing vector holds, so only the axis being varied is listed.
private struct FormfeedEmitVector: Decodable {
    let format: String
    let mode: String
    let expected: String
}

private struct FormfeedVector: Decodable {
    let inputHex: String
    /// Printstream shape (`variant` + `columnar` only), same as job-007's.
    let document: PrintstreamDocumentVector
    let emit: [FormfeedEmitVector]

    enum CodingKeys: String, CodingKey {
        case inputHex = "input_hex"
        case document
        case emit
    }
}

private struct Job010VectorFile: Decodable {
    let convert: [ConvertVector]
    let formfeedPrintstream: FormfeedVector
    let note: String

    enum CodingKeys: String, CodingKey {
        case convert
        case formfeedPrintstream = "formfeed_printstream"
        case note
    }
}

private func loadJob010Vectors() throws -> Job010VectorFile {
    let url = try #require(
        Bundle.module.url(forResource: "job-010-vectors", withExtension: "json"),
        "job-010-vectors.json missing from the test bundle"
    )
    return try JSONDecoder().decode(Job010VectorFile.self, from: Data(contentsOf: url))
}

private func loadJob008Vectors() throws -> Job008VectorFile {
    let url = try #require(
        Bundle.module.url(forResource: "job-008-vectors", withExtension: "json"),
        "job-008-vectors.json missing from the test bundle"
    )
    return try JSONDecoder().decode(Job008VectorFile.self, from: Data(contentsOf: url))
}

/// Shared block/line/span/style comparison, used by both the parse_ws and
/// parse_printstream vector suites.
private func assertBlocks(_ got: [Block], _ want: [BlockVector], label: String) {
    #expect(got.count == want.count, "\(label): block count")
    for (b, wantBlock) in want.enumerated() where b < got.count {
        let gotBlock = got[b]
        #expect(gotBlock.kind.rawValue == wantBlock.kind, "\(label) block \(b): kind")
        #expect(gotBlock.heading == wantBlock.heading, "\(label) block \(b): heading")
        #expect(gotBlock.lines.count == wantBlock.lines.count, "\(label) block \(b): line count")
        for (l, wantLine) in wantBlock.lines.enumerated() where l < gotBlock.lines.count {
            let gotSpans = gotBlock.lines[l].spans
            #expect(gotSpans.count == wantLine.count, "\(label) block \(b) line \(l): span count")
            for (s, wantSpan) in wantLine.enumerated() where s < gotSpans.count {
                #expect(gotSpans[s].text == wantSpan.text,
                        "\(label) block \(b) line \(l) span \(s): text")
                #expect(styleCodes(gotSpans[s].styles) == wantSpan.styles.sorted(),
                        "\(label) block \(b) line \(l) span \(s): styles")
            }
        }
    }
}

/// `Style` -> the Python style-code strings the vectors use, sorted for comparison.
/// Lives in the test target: the codes are the Python wire format, and nothing in
/// `Sources/` needs them until an emitter does.
private func styleCodes(_ style: Style) -> [String] {
    var codes: [String] = []
    if style.contains(.bold) { codes.append("b") }
    if style.contains(.italic) { codes.append("i") }
    if style.contains(.underline) { codes.append("u") }
    if style.contains(.sup) { codes.append("sup") }
    if style.contains(.sub) { codes.append("sub") }
    if style.contains(.strike) { codes.append("strike") }
    if style.contains(.fnref) { codes.append("fnref") }
    return codes.sorted()
}

private func bytesFromHex(_ hex: String) -> [UInt8] {
    let chars = Array(hex)
    precondition(chars.count % 2 == 0, "hex string must have an even length")
    var out: [UInt8] = []
    out.reserveCapacity(chars.count / 2)
    for i in stride(from: 0, to: chars.count, by: 2) {
        out.append(UInt8(String(chars[i...(i + 1)]), radix: 16)!)
    }
    return out
}

private func hexFromBytes(_ bytes: [UInt8]) -> String {
    bytes.map { String(format: "%02x", $0) }.joined()
}

@Test func detectMatchesPythonVectors() throws {
    let vectors = try loadVectors().detect
    #expect(vectors.count == 7)
    for (i, v) in vectors.enumerated() {
        let got = detect(bytesFromHex(v.inputHex))
        #expect(got.variant.rawValue == v.variant, "detect vector \(i): variant")
        if let expected = v.softReturns {
            #expect(got.softReturns == expected, "detect vector \(i): soft_returns")
        }
        if let expected = v.hardReturns {
            #expect(got.hardReturns == expected, "detect vector \(i): hard_returns")
        }
        if let expected = v.highBitBytes {
            #expect(got.highBitBytes == expected, "detect vector \(i): high_bit_bytes")
        }
        if let expected = v.textPct {
            #expect(got.textPct == expected, "detect vector \(i): text_pct")
        }
        if let expected = v.symmetricBlocks1D {
            #expect(got.symmetricBlocks1D == expected, "detect vector \(i): symmetric_blocks_1d")
        }
        if let expected = v.size {
            #expect(got.size == expected, "detect vector \(i): size")
        }
    }
}

private func assertLinesPassVector(_ v: LinesPassVector, label: String) {
    let got = linesPass(bytesFromHex(v.inputHex))
    #expect(got.margin == v.margin, "\(label): margin")
    #expect(got.lines.count == v.lines.count, "\(label): line count")
    for (j, expected) in v.lines.enumerated() where j < got.lines.count {
        let line = got.lines[j]
        #expect(line.separator.rawValue == expected.sep, "\(label) line \(j): sep")
        #expect(hexFromBytes(line.text) == expected.textHex, "\(label) line \(j): text")
    }
}

@Test func linesPassMatchesPythonVectors() throws {
    let vectors = try loadVectors().linesPass
    #expect(vectors.count == 8)
    for (i, v) in vectors.enumerated() {
        assertLinesPassVector(v, label: "lines_pass vector \(i)")
    }
}

@Test func cp437TableMatchesPythonVectors() throws {
    let table = try loadJob004Vectors().cp437ByteToUnicodeCodepoint
    #expect(table.count == 256)
    for byte in 0...255 {
        let key = String(format: "%02x", byte)
        let expected = try #require(table[key], "cp437 vector missing byte 0x\(key)")
        let decoded = decodeCP437([UInt8(byte)])
        let scalar = try #require(decoded.unicodeScalars.first, "byte 0x\(key) decoded to empty string")
        #expect(Int(scalar.value) == expected, "cp437 byte 0x\(key)")
    }
}

@Test func symmetricBlocksMatchesPythonVectors() throws {
    // job-005 predates ctrl-kd 1.2.0's note-kind fix: it was machine-generated from
    // Python 1.1.3, whose `_note_text` took the wrong byte segment (see
    // SymmetricBlocks.swift's `parseNote` doc comment) -- and, worse, its own
    // synthetic note-block INPUT bytes were built to the same pre-1.2.0
    // (spec-incorrect) shape those old vectors' `footnotes` strings describe. Feeding
    // that old-shaped input through the NEW, spec-correct `parseNote` does not, and
    // should not, reproduce those exact strings (proven against the real Python 1.2.0
    // reference: it returns empty text for every one of these inputs too, not a
    // crash). What's still valid, and still asserted here: the rewritten byte stream
    // (sentinel injection for headings/softpage/tabs is unchanged) and that a note is
    // still recognized and counted for every case the old vectors called a footnote.
    // Real note-TEXT extraction is covered by `notesVectors1_2_0` below, against
    // ground truth generated by the actual fixed implementation.
    let vectors = try loadJob005Vectors().symmetricBlocks
    #expect(vectors.count == 7)
    for (i, v) in vectors.enumerated() {
        let got = symmetricBlocks(bytesFromHex(v.inputHex))
        #expect(hexFromBytes(got.bytes) == v.outputHex, "symmetric_blocks vector \(i): bytes")
        #expect(got.notes.count == v.footnotes.count, "symmetric_blocks vector \(i): note count")
    }
}

@Test func parseWSMatchesPythonVectors() throws {
    let vectors = try loadJob006Vectors().parseWS
    #expect(vectors.count == 7)
    for (i, v) in vectors.enumerated() {
        let doc = parseWS(bytesFromHex(v.inputHex))
        let want = v.document
        let label = "parse_ws vector \(i)"

        // meta
        #expect(doc.detection?.variant.rawValue == want.meta.variant, "\(label): variant")
        #expect(doc.marginEstimate == want.meta.marginEstimate, "\(label): margin_estimate")
        #expect(doc.dotCommands == want.meta.dotCommands, "\(label): dot_commands")
        #expect(doc.columnar == want.meta.columnar, "\(label): columnar")
        var wantUnknown: [UInt8: Int] = [:]
        for (key, count) in want.meta.unknownCodes {
            let hex = key.hasPrefix("0x") ? String(key.dropFirst(2)) : key
            wantUnknown[UInt8(hex, radix: 16)!] = count
        }
        #expect(doc.unknownCodes == wantUnknown, "\(label): unknown_codes")

        // footnotes: job-006 predates ctrl-kd 1.2.0's note-kind fix (see the doc
        // comment on `symmetricBlocksMatchesPythonVectors` above for the full
        // explanation) — vector 4's expected text ("See the accords.") was extracted
        // by the old, since-replaced algorithm from an old-shaped synthetic block, so
        // it's no longer reproducible (nor should it be) under the correct
        // `parseNote`. Real note-text extraction is covered by `notesVectors1_2_0`
        // against ground truth from the actual fixed implementation; what's still
        // valid here is that the same NUMBER of footnotes is still recognized.
        let gotFootnotes = doc.footnotes.map { $0.map(\.text).joined() }
        #expect(gotFootnotes.count == want.footnotes.count, "\(label): footnote count")

        // blocks / lines / spans / styles
        assertBlocks(doc.blocks, want.blocks, label: label)
    }
}

@Test func parsePrintstreamMatchesPythonVectors() throws {
    let vectors = try loadJob007Vectors().parsePrintstream
    #expect(vectors.count == 6)
    for (i, v) in vectors.enumerated() {
        let doc = parsePrintstream(bytesFromHex(v.inputHex))
        let want = v.document
        let label = "parse_printstream vector \(i)"

        #expect(doc.detection?.variant.rawValue == want.meta.variant, "\(label): variant")
        #expect(doc.columnar == want.meta.columnar, "\(label): columnar")
        // Never runs the wrap test, so there is no margin to report.
        #expect(doc.marginEstimate == nil, "\(label): marginEstimate should be nil")
        #expect(doc.footnotes.map { $0.map(\.text).joined() } == want.footnotes,
                "\(label): footnotes")
        assertBlocks(doc.blocks, want.blocks, label: label)
    }
}

@Test func emittersMatchPythonVectors() throws {
    let vectors = try loadJob008Vectors().emit
    #expect(vectors.count == 28)
    for v in vectors {
        if staleFootnoteVectorNames.contains(v.name) { continue }   // see file-top comment
        let doc = try parse(bytesFromHex(v.inputHex))
        let mode = try #require(EmitMode(rawValue: v.mode), "unknown mode \(v.mode)")
        let got: String
        switch v.format {
        case "text": got = emitText(doc, mode: mode)
        case "markdown": got = emitMarkdown(doc, mode: mode)
        default:
            Issue.record("unknown format \(v.format) in vector \(v.name)")
            continue
        }
        // Verbatim comparison — trailing whitespace and the final newline are part of the
        // contract, so nothing is trimmed on either side.
        #expect(got == v.expected, "emit vector \(v.name)")
    }
}

@Test func htmlAndRTFEmittersMatchPythonVectors() throws {
    let vectors = try loadJob009Vectors().emit2
    #expect(vectors.count == 33)
    for v in vectors {
        if staleFootnoteVectorNames.contains(v.name) { continue }   // see file-top comment
        let doc = try parse(bytesFromHex(v.inputHex))
        let mode = try #require(EmitMode(rawValue: v.mode), "unknown mode \(v.mode)")
        let got: String
        switch v.format {
        case "html": got = emitHTML(doc, mode: mode, options: EmitOptions(title: v.title ?? ""))
        case "rtf": got = emitRTF(doc, mode: mode)
        default:
            Issue.record("unknown format \(v.format) in vector \(v.name)")
            continue
        }
        // see strippingNotesCSS: every html vector here predates 1.2.0's unconditional CSS
        // addition, a no-op for every other format.
        let comparable = v.format == "html" ? strippingNotesCSS(got) : got
        #expect(comparable == v.expected, "emit2 vector \(v.name)")
    }
}

@Test func convertMatchesPythonVectors() throws {
    // One vector per built-in format plus the `md` alias, all through the front door — so
    // these prove the registry wires each name to the right emitter, not just that the
    // emitters work (job-008/009's vectors already did that).
    let vectors = try loadJob010Vectors().convert
    #expect(vectors.count == 5)
    for v in vectors {
        let got = try convert(bytesFromHex(v.inputHex), to: v.to)
        // see strippingNotesCSS
        let comparable = v.to == "html" ? strippingNotesCSS(got) : got
        #expect(comparable == v.expected, "convert vector to=\(v.to)")
    }
}

@Test func formfeedPrintstreamMatchesPythonVectors() throws {
    // The case the job-009 response asked for: a print capture bracketed AND separated by
    // form feeds, so the document has empty paragraphs at both edges and between the pages.
    // That shape exercises every emitter's empty-block guard at once — the guards job-009's
    // mutation run found were unproven by its own 33 vectors.
    let v = try loadJob010Vectors().formfeedPrintstream
    let doc = try parse(bytesFromHex(v.inputHex))
    let want = v.document

    #expect(doc.detection?.variant.rawValue == want.meta.variant, "formfeed document: variant")
    #expect(doc.columnar == want.meta.columnar, "formfeed document: columnar")
    #expect(doc.marginEstimate == nil, "formfeed document: marginEstimate should be nil")
    #expect(doc.footnotes.map { $0.map(\.text).joined() } == want.footnotes,
            "formfeed document: footnotes")
    assertBlocks(doc.blocks, want.blocks, label: "formfeed document")

    // All four emitters, both modes — the emitters called directly, since the convert
    // vectors above cover the registry path.
    #expect(v.emit.count == 8)
    for e in v.emit {
        let mode = try #require(EmitMode(rawValue: e.mode), "unknown mode \(e.mode)")
        let got: String
        switch e.format {
        case "text": got = emitText(doc, mode: mode)
        case "markdown": got = emitMarkdown(doc, mode: mode)
        case "html": got = emitHTML(doc, mode: mode)
        case "rtf": got = emitRTF(doc, mode: mode)
        default:
            Issue.record("unknown format \(e.format) in formfeed vector")
            continue
        }
        // see strippingNotesCSS
        let comparable = e.format == "html" ? strippingNotesCSS(got) : got
        #expect(comparable == e.expected, "formfeed emit \(e.format)/\(e.mode)")
    }
}

@Test func parseFrontDoorRoutesPythonVectors() throws {
    let vectors = try loadJob007Vectors().parseFrontDoor
    #expect(vectors.count == 2)
    for (i, v) in vectors.enumerated() {
        let data = bytesFromHex(v.inputHex)
        let label = "parse_front_door vector \(i)"
        if v.routesTo == "REFUSES" {
            #expect(throws: ParseError.self, "\(label): expected refusal") {
                _ = try parse(data)
            }
        } else {
            let doc = try parse(data)
            #expect(doc.detection?.variant.rawValue == v.routesTo, "\(label): routed variant")
        }
    }
}

@Test func symmetricBlocksExtraVectors() throws {
    // The NBSP note-strip case, folded into the canonical vector set per job-005's
    // request — this replaces the hand-authored fixture that lived in
    // SymmetricBlocksTests.swift. Same pre-1.2.0-shape caveat as
    // `symmetricBlocksMatchesPythonVectors` above: this vector's input bytes predate
    // the real note-block layout, so its exact NBSP-stripped text is no longer
    // reproducible (nor should it be) under the correct `parseNote`. The NBSP-strip
    // behavior itself is still exercised, on a correctly-shaped block, by
    // `noteTextStripsNBSPAndDotCommands` in ParseWSTests.swift.
    let vectors = try loadJob006Vectors().symmetricBlocksExtra
    #expect(vectors.count == 1)
    for (i, v) in vectors.enumerated() {
        let got = symmetricBlocks(bytesFromHex(v.inputHex))
        #expect(hexFromBytes(got.bytes) == v.outputHex, "symmetric_blocks_extra \(i): bytes")
        #expect(got.notes.count == v.footnotes.count, "symmetric_blocks_extra \(i): note count")
    }
}

@Test func bareLFClassifiesAsHard() throws {
    // job-003 flagged a lone 0x0A as unproven by the vector suite: it classifies as
    // `hard` (brk[0] != 0x8D at core.py:116), which is easy to get backwards. This
    // vector (job-004-vectors.md's lines_pass_extra) closes that gap.
    let vectors = try loadJob004Vectors().linesPassExtra
    #expect(vectors.count == 1)
    for (i, v) in vectors.enumerated() {
        assertLinesPassVector(v, label: "lines_pass_extra vector \(i)")
    }
}

// MARK: - job-011 (PDF layout half: constants, _wrap_line, _coalesce, _doc_to_pagelines)

private struct Job011VectorFile: Decodable {
    let constants: [String: Int]
    let wrapLine: [WrapLineVector]
    let coalesce: [CoalesceVector]
    let docToPagelines: [PagelinesVector]

    enum CodingKeys: String, CodingKey {
        case constants
        case wrapLine = "wrap_line"
        case coalesce
        case docToPagelines = "doc_to_pagelines"
    }
}

private struct WrapLineVector: Decodable {
    let spans: [SpanVector]
    let width: Int
    /// Segment-lines: one list of styled segments per wrapped line.
    let expected: [[SpanVector]]
}

private struct CoalesceVector: Decodable {
    let line: [SpanVector]
    let expected: [SpanVector]
}

private struct PagelinesVector: Decodable {
    let name: String
    let inputHex: String
    let printed: Bool
    /// Pages -> lines -> segments.
    let pages: [[[SpanVector]]]

    enum CodingKeys: String, CodingKey {
        case name
        case inputHex = "input_hex"
        case printed
        case pages
    }
}

private func loadJob011Vectors() throws -> Job011VectorFile {
    let url = try #require(
        Bundle.module.url(forResource: "job-011-vectors", withExtension: "json"),
        "job-011-vectors.json missing from the test bundle"
    )
    return try JSONDecoder().decode(Job011VectorFile.self, from: Data(contentsOf: url))
}

/// The vectors' style-code strings -> `Style`. The inverse of `styleCodes`, needed here
/// because job-011 is the first vector set whose INPUT carries styles.
private func styleFromCodes(_ codes: [String]) -> Style {
    var style: Style = []
    for code in codes {
        switch code {
        case "b": style.insert(.bold)
        case "i": style.insert(.italic)
        case "u": style.insert(.underline)
        case "sup": style.insert(.sup)
        case "sub": style.insert(.sub)
        case "strike": style.insert(.strike)
        case "fnref": style.insert(.fnref)
        default: Issue.record("unknown style code \(code) in a job-011 vector")
        }
    }
    return style
}

private func spans(_ vectors: [SpanVector]) -> [Span] {
    vectors.map { Span(text: $0.text, styles: styleFromCodes($0.styles)) }
}

/// Assert one laid-out line segment by segment, so a failure names the segment.
private func assertPageLine(_ got: PageLine, _ want: [SpanVector], label: String) {
    #expect(got.count == want.count, "\(label): segment count")
    for (i, wantSegment) in want.enumerated() where i < got.count {
        #expect(got[i].text == wantSegment.text, "\(label) segment \(i): text")
        #expect(styleCodes(got[i].styles) == wantSegment.styles.sorted(),
                "\(label) segment \(i): styles")
    }
}

@Test func pdfConstantsMatchPython() throws {
    // Taken from the vectors rather than recomputed — MAX_COLS in particular, whose Python
    // expression only lands on 65 because `int()` truncates 65.00000000000001.
    //
    // `want` still carries 10 entries including `LINES_PRINTED` — this file was
    // machine-generated from Python 1.2.0, before ctrl-kd 1.3.0 deleted that constant
    // (`pdf.py`'s own `LINES_PRINTED` -- printed capacity is per-document now, from
    // WordStar's own vertical model; see `PDFLayout.swift`'s `printedCap`). Regenerating
    // this vector file to drop the now-nonexistent Python constant would erase real
    // ground truth for the nine that remain, so it stays as captured; the Swift side just
    // stops asserting on the one entry with no live counterpart to check against.
    let want = try loadJob011Vectors().constants
    #expect(want.count == 10)
    #expect(PDFMetrics.pageWidth == want["PAGE_W"])
    #expect(PDFMetrics.pageHeight == want["PAGE_H"])
    #expect(PDFMetrics.margin == want["MARGIN"])
    #expect(PDFMetrics.size == want["SIZE"])
    #expect(PDFMetrics.lead == want["LEAD"])
    #expect(PDFMetrics.topModern == want["TOP_MODERN"])
    #expect(PDFMetrics.topPrinted == want["TOP_PRINTED"])
    #expect(PDFMetrics.linesModern == want["LINES_MODERN"])
    #expect(PDFMetrics.maxCols == want["MAX_COLS"])
}

@Test func wrapLineMatchesPythonVectors() throws {
    // Four cases: a line that fits, a styled line with a preserved leading indent at a
    // narrow width, a word longer than the column, and a 30-word wrap at the real 65.
    let vectors = try loadJob011Vectors().wrapLine
    #expect(vectors.count == 4)
    for (i, v) in vectors.enumerated() {
        let got = wrapLine(spans(v.spans), width: v.width)
        #expect(got.count == v.expected.count, "wrap_line \(i) (width \(v.width)): line count")
        for (l, wantLine) in v.expected.enumerated() where l < got.count {
            assertPageLine(got[l], wantLine, label: "wrap_line \(i) line \(l)")
        }
    }
}

@Test func coalesceMatchesPythonVectors() throws {
    let vectors = try loadJob011Vectors().coalesce
    #expect(vectors.count == 1)
    for (i, v) in vectors.enumerated() {
        assertPageLine(coalesce(spans(v.line)), v.expected, label: "coalesce \(i)")
    }
}

@Test func docToPagelinesMatchesPythonVectors() throws {
    // Five documents x modern/printed. The subtle one is chapter_drop_print/printed, where
    // page 1's leading blanks are the author's chapter drop and must survive while the
    // uniform machine margin on page 2 is stripped from both.
    let vectors = try loadJob011Vectors().docToPagelines
    #expect(vectors.count == 10)
    for v in vectors {
        if staleFootnoteVectorNames.contains(v.name) { continue }   // see file-top comment
        let doc = try parse(bytesFromHex(v.inputHex))
        let got = docToPagelines(doc, printed: v.printed)
        #expect(got.count == v.pages.count, "\(v.name): page count")
        for (p, wantPage) in v.pages.enumerated() where p < got.count {
            #expect(got[p].count == wantPage.count, "\(v.name) page \(p): line count")
            for (l, wantLine) in wantPage.enumerated() where l < got[p].count {
                assertPageLine(got[p][l], wantLine, label: "\(v.name) page \(p) line \(l)")
            }
        }
    }
}

// MARK: - job-012 (PDF writer half: _esc, _page_stream, emit_pdf — plus the 1.1.5 layout fixes)

private struct Job012VectorFile: Decodable {
    let layoutUpdates: [PagelinesVector]
    let esc: [EscVector]
    let pageStream: [PageStreamVector]
    let emitPDF: [EmitPDFVector]

    enum CodingKeys: String, CodingKey {
        case layoutUpdates = "layout_updates"
        case esc
        case pageStream = "page_stream"
        case emitPDF = "emit_pdf"
    }
}

private struct EscVector: Decodable {
    let text: String
    let expectedHex: String

    enum CodingKeys: String, CodingKey {
        case text
        case expectedHex = "expected_hex"
    }
}

private struct PageStreamVector: Decodable {
    let name: String
    /// Lines -> segments. Pre-laid-out: these go straight to `pageStream`, bypassing the
    /// layout half, which is what lets a case carry styles no real document produces.
    let pagelines: [[SpanVector]]
    let top: Int
    let expectedHex: String

    enum CodingKeys: String, CodingKey {
        case name, pagelines, top
        case expectedHex = "expected_hex"
    }
}

private struct EmitPDFVector: Decodable {
    let name: String
    let inputHex: String
    let mode: String
    let expectedHex: String

    enum CodingKeys: String, CodingKey {
        case name, mode
        case inputHex = "input_hex"
        case expectedHex = "expected_hex"
    }
}

private func loadJob012Vectors() throws -> Job012VectorFile {
    let url = try #require(
        Bundle.module.url(forResource: "job-012-vectors", withExtension: "json"),
        "job-012-vectors.json missing from the test bundle"
    )
    return try JSONDecoder().decode(Job012VectorFile.self, from: Data(contentsOf: url))
}

/// The job-012 vector cases whose pinned output was a Python **bug** that 1.1.6 then fixed,
/// with the transformation from the old ground truth to the new one.
///
/// Exactly one case qualifies. `exact_fill_no_blank_sheet/modern` pinned `[53, 0]` — a trailing
/// empty page, i.e. the blank sheet the vector's own name says should not exist (job-012 called
/// this out: honest ground truth, misleading label). 1.1.6 pops that page, so the case is now
/// `[53]`.
///
/// The job-012 JSON is left exactly as Athena generated it, because it is a correct record of
/// what 1.1.5 did and rewriting delivered ground truth to match a later version would destroy
/// the only evidence that the version changed. Instead the expectation is DERIVED here by the
/// documented fix — drop trailing empty pages — which keeps the case asserting something: if
/// the pop breaks, `[53, 0]` comes back and this fails.
private let job012CasesFixedIn116: Set<String> = ["exact_fill_no_blank_sheet/modern"]

@Test func layoutUpdatesMatchPython116Vectors() throws {
    // The two 1.1.5 layout fixes, generated from the fixed Python: heading blocks render
    // bold, and a trailing empty page is popped.
    //
    // Parsed through `parse()`, matching job-011's harness — and it MATTERS here in a way it
    // did not there. Both exact-fill documents are plain text with hard returns only, which
    // `detect()` classifies as `printstream`; `parseWS` on the same bytes produces a
    // different block structure and neither exact-fill case reproduces. The vectors' own
    // `printed` flag is still honored as given, so the printstream document gets laid out
    // both ways.
    //
    // Three of the four cases still hold at 1.1.6 unchanged; the fourth is adjusted by
    // `job012CasesFixedIn116` above. Verified against the local reference at both versions.
    let vectors = try loadJob012Vectors().layoutUpdates
    #expect(vectors.count == 4)
    for v in vectors {
        var want = v.pages
        if job012CasesFixedIn116.contains(v.name) {
            let before = want.count
            while want.count > 1, want[want.count - 1].isEmpty {
                want.removeLast()
            }
            #expect(want.count < before,
                    "\(v.name) is listed as fixed in 1.1.6 but pins no trailing empty page")
        }

        let doc = try parse(bytesFromHex(v.inputHex))
        let got = docToPagelines(doc, printed: v.printed)
        #expect(got.count == want.count, "\(v.name): page count")
        for (p, wantPage) in want.enumerated() where p < got.count {
            #expect(got[p].count == wantPage.count, "\(v.name) page \(p): line count")
            for (l, wantLine) in wantPage.enumerated() where l < got[p].count {
                assertPageLine(got[p][l], wantLine, label: "\(v.name) page \(p) line \(l)")
            }
        }
    }
}

// MARK: - job-013 (the REAL exact-fill fix: the pop moved after the stripping, Python 1.1.6)

private struct Job013VectorFile: Decodable {
    let layout116: [Pagelines116Vector]

    enum CodingKeys: String, CodingKey {
        case layout116 = "layout_116"
    }
}

/// job-011's `PagelinesVector` plus the `parser` field, added at job-012's suggestion.
///
/// It closes a real ambiguity rather than restating the obvious: `input_hex` + `printed` only
/// specifies a case if you also know which parser produced the document, and for these inputs
/// the two disagree — job-012 lost twenty minutes to assuming `parseWS` for bytes that only
/// reproduce through `parse()`. A case where both parsers agree teaches nothing about which
/// was meant, which is exactly when the assumption goes unnoticed.
private struct Pagelines116Vector: Decodable {
    let name: String
    let inputHex: String
    /// `"parse"` (the front door, which runs `detect`) or `"parse_ws"`.
    let parser: String
    let printed: Bool
    let pages: [[[SpanVector]]]

    enum CodingKeys: String, CodingKey {
        case name, parser, printed, pages
        case inputHex = "input_hex"
    }
}

private func loadJob013Vectors() throws -> Job013VectorFile {
    let url = try #require(
        Bundle.module.url(forResource: "job-013-vectors", withExtension: "json"),
        "job-013-vectors.json missing from the test bundle"
    )
    return try JSONDecoder().decode(Job013VectorFile.self, from: Data(contentsOf: url))
}

@Test func layout116MatchesPythonVectors() throws {
    // Six cases, three documents x modern/printed:
    //
    //   exact_fill_true_boundary       the case 1.1.5's fix was aimed at and missed. This is
    //                                 the ONE case here with teeth against 1.1.5 — it gives
    //                                 [54, 0] there and [54] at 1.1.6. Confirmed by running
    //                                 all six against a local v1.1.5 checkout.
    //   trailing_double_pa            the pop path that always worked.
    //   interior_double_pa_preserved  the page the pop must NOT take: [1, 0, 1].
    //
    // The last two pass on 1.1.5 as well, which makes them regression guards rather than
    // proof of the fix — worth saying, because "six new vectors" would otherwise imply six
    // new bug-detecting cases.
    let vectors = try loadJob013Vectors().layout116
    #expect(vectors.count == 6)
    for v in vectors {
        let data = bytesFromHex(v.inputHex)
        let doc: Document
        switch v.parser {
        case "parse": doc = try parse(data)
        case "parse_ws": doc = parseWS(data)
        default:
            Issue.record("\(v.name): unknown parser \(v.parser)")
            continue
        }
        let got = docToPagelines(doc, printed: v.printed)
        #expect(got.count == v.pages.count,
                "\(v.name): page count (got \(got.map(\.count)))")
        for (p, wantPage) in v.pages.enumerated() where p < got.count {
            #expect(got[p].count == wantPage.count, "\(v.name) page \(p): line count")
            for (l, wantLine) in wantPage.enumerated() where l < got[p].count {
                assertPageLine(got[p][l], wantLine, label: "\(v.name) page \(p) line \(l)")
            }
        }
    }
}

@Test func escMatchesPythonVectors() throws {
    // Six cases: plain, parens, backslash, all three mixed, and two non-Latin-1 inputs that
    // must degrade to '?' — an em dash and U+0141.
    let vectors = try loadJob012Vectors().esc
    #expect(vectors.count == 6)
    for v in vectors {
        #expect(hexFromBytes(esc(v.text)) == v.expectedHex, "esc(\(v.text.debugDescription))")
    }
}

@Test func pageStreamMatchesPythonVectors() throws {
    // Six cases: plain two lines, styled runs, the underline's half-point coordinates,
    // sup/sub rise, strike, and a coalesce that must happen before any operator is emitted.
    let vectors = try loadJob012Vectors().pageStream
    #expect(vectors.count == 6)
    for v in vectors {
        let page: Page = v.pagelines.map { spans($0) }
        let got = pageStream(page, top: v.top)
        #expect(hexFromBytes(got) == v.expectedHex, "page_stream \(v.name)")
        // On a mismatch the hex is unreadable; show the operators.
        if hexFromBytes(got) != v.expectedHex {
            Issue.record("""
            page_stream \(v.name)
              got:  \(String(decoding: got))
              want: \(String(decoding: bytesFromHex(v.expectedHex)))
            """)
        }
    }
}

@Test func emitPDFMatchesPythonVectorsByteForByte() throws {
    // Two complete PDFs, byte-identical or bust: a modern ws4 document, and a print stream
    // with a form feed that becomes two pages. These pin the object numbering, the /Length
    // of every stream, all ten-digit xref offsets, and startxref — a single byte moved
    // anywhere earlier in the file shifts every offset after it, so this is the test that
    // proves the assembly rather than the pieces.
    let vectors = try loadJob012Vectors().emitPDF
    #expect(vectors.count == 2)
    for v in vectors {
        let mode = try #require(EmitMode(rawValue: v.mode), "\(v.name): unknown mode \(v.mode)")
        let got = emitPDF(try parse(bytesFromHex(v.inputHex)), mode: mode)
        let want = bytesFromHex(v.expectedHex)
        #expect(got.count == want.count, "\(v.name): byte count")
        #expect(got == want, "\(v.name): bytes")
        if got != want, let at = zip(got, want).enumerated().first(where: { $0.1.0 != $0.1.1 })?.0 {
            let from = max(0, at - 40)
            Issue.record("""
            \(v.name): first difference at byte \(at)
              got:  ...\(String(decoding: Array(got[from..<min(got.count, at + 40)])))
              want: ...\(String(decoding: Array(want[from..<min(want.count, at + 40)])))
            """)
        }
    }
}

/// Latin-1 back to a `String` for failure messages — the writer's own encoding, reversed, so
/// a PDF operator prints as itself rather than as hex.
private func String(decoding bytes: [UInt8]) -> Swift.String {
    Swift.String(bytes.map { Character(Unicode.Scalar($0)) })
}
