import Foundation
import Testing
@testable import CtrlKD

/// Equivalence proof against `Resources/job-003-vectors.json` — machine-generated by
/// the Python ctrl-kd 1.1.3 implementation. Every vector must reproduce exactly.
///
/// `Foundation` is imported here for `JSONDecoder`/`Bundle` only; the `CtrlKD` library
/// target itself stays Foundation-free.

private struct VectorFile: Decodable {
    let detect: [DetectVector]
    let linesPass: [LinesPassVector]
    let note: String

    enum CodingKeys: String, CodingKey {
        case detect
        case linesPass = "lines_pass"
        case note
    }
}

private struct DetectVector: Decodable {
    let inputHex: String
    let variant: String
    // Absent for the empty / ^Z-at-start vectors: Python's detect() returns those before
    // it computes any evidence, so there is nothing to assert for them.
    let softReturns: Int?
    let hardReturns: Int?
    let highBitBytes: Int?
    let textPct: Int?
    let symmetricBlocks1D: Int?
    let size: Int?

    enum CodingKeys: String, CodingKey {
        case inputHex = "input_hex"
        case variant
        case softReturns = "soft_returns"
        case hardReturns = "hard_returns"
        case highBitBytes = "high_bit_bytes"
        case textPct = "text_pct"
        case symmetricBlocks1D = "symmetric_blocks_1d"
        case size
    }
}

private struct LinesPassVector: Decodable {
    let inputHex: String
    let margin: Int
    let lines: [LineVector]

    enum CodingKeys: String, CodingKey {
        case inputHex = "input_hex"
        case margin
        case lines
    }
}

private struct LineVector: Decodable {
    let textHex: String
    let sep: String

    enum CodingKeys: String, CodingKey {
        case textHex = "text_hex"
        case sep
    }
}

private struct Job004VectorFile: Decodable {
    let cp437ByteToUnicodeCodepoint: [String: Int]
    let linesPassExtra: [LinesPassVector]
    let note: String

    enum CodingKeys: String, CodingKey {
        case cp437ByteToUnicodeCodepoint = "cp437_byte_to_unicode_codepoint"
        case linesPassExtra = "lines_pass_extra"
        case note
    }
}

private func loadVectors() throws -> VectorFile {
    let url = try #require(
        Bundle.module.url(forResource: "job-003-vectors", withExtension: "json"),
        "job-003-vectors.json missing from the test bundle"
    )
    return try JSONDecoder().decode(VectorFile.self, from: Data(contentsOf: url))
}

private func loadJob004Vectors() throws -> Job004VectorFile {
    let url = try #require(
        Bundle.module.url(forResource: "job-004-vectors", withExtension: "json"),
        "job-004-vectors.json missing from the test bundle"
    )
    return try JSONDecoder().decode(Job004VectorFile.self, from: Data(contentsOf: url))
}

private struct SymmetricBlocksVector: Decodable {
    let inputHex: String
    let outputHex: String
    let footnotes: [String]

    enum CodingKeys: String, CodingKey {
        case inputHex = "input_hex"
        case outputHex = "output_hex"
        case footnotes
    }
}

private struct Job005VectorFile: Decodable {
    let symmetricBlocks: [SymmetricBlocksVector]
    let note: String

    enum CodingKeys: String, CodingKey {
        case symmetricBlocks = "symmetric_blocks"
        case note
    }
}

private func loadJob005Vectors() throws -> Job005VectorFile {
    let url = try #require(
        Bundle.module.url(forResource: "job-005-vectors", withExtension: "json"),
        "job-005-vectors.json missing from the test bundle"
    )
    return try JSONDecoder().decode(Job005VectorFile.self, from: Data(contentsOf: url))
}

private func bytesFromHex(_ hex: String) -> [UInt8] {
    let chars = Array(hex)
    precondition(chars.count % 2 == 0, "hex string must have an even length")
    var out: [UInt8] = []
    out.reserveCapacity(chars.count / 2)
    for i in stride(from: 0, to: chars.count, by: 2) {
        out.append(UInt8(String(chars[i...(i + 1)]), radix: 16)!)
    }
    return out
}

private func hexFromBytes(_ bytes: [UInt8]) -> String {
    bytes.map { String(format: "%02x", $0) }.joined()
}

@Test func detectMatchesPythonVectors() throws {
    let vectors = try loadVectors().detect
    #expect(vectors.count == 7)
    for (i, v) in vectors.enumerated() {
        let got = detect(bytesFromHex(v.inputHex))
        #expect(got.variant.rawValue == v.variant, "detect vector \(i): variant")
        if let expected = v.softReturns {
            #expect(got.softReturns == expected, "detect vector \(i): soft_returns")
        }
        if let expected = v.hardReturns {
            #expect(got.hardReturns == expected, "detect vector \(i): hard_returns")
        }
        if let expected = v.highBitBytes {
            #expect(got.highBitBytes == expected, "detect vector \(i): high_bit_bytes")
        }
        if let expected = v.textPct {
            #expect(got.textPct == expected, "detect vector \(i): text_pct")
        }
        if let expected = v.symmetricBlocks1D {
            #expect(got.symmetricBlocks1D == expected, "detect vector \(i): symmetric_blocks_1d")
        }
        if let expected = v.size {
            #expect(got.size == expected, "detect vector \(i): size")
        }
    }
}

private func assertLinesPassVector(_ v: LinesPassVector, label: String) {
    let got = linesPass(bytesFromHex(v.inputHex))
    #expect(got.margin == v.margin, "\(label): margin")
    #expect(got.lines.count == v.lines.count, "\(label): line count")
    for (j, expected) in v.lines.enumerated() where j < got.lines.count {
        let line = got.lines[j]
        #expect(line.separator.rawValue == expected.sep, "\(label) line \(j): sep")
        #expect(hexFromBytes(line.text) == expected.textHex, "\(label) line \(j): text")
    }
}

@Test func linesPassMatchesPythonVectors() throws {
    let vectors = try loadVectors().linesPass
    #expect(vectors.count == 8)
    for (i, v) in vectors.enumerated() {
        assertLinesPassVector(v, label: "lines_pass vector \(i)")
    }
}

@Test func cp437TableMatchesPythonVectors() throws {
    let table = try loadJob004Vectors().cp437ByteToUnicodeCodepoint
    #expect(table.count == 256)
    for byte in 0...255 {
        let key = String(format: "%02x", byte)
        let expected = try #require(table[key], "cp437 vector missing byte 0x\(key)")
        let decoded = decodeCP437([UInt8(byte)])
        let scalar = try #require(decoded.unicodeScalars.first, "byte 0x\(key) decoded to empty string")
        #expect(Int(scalar.value) == expected, "cp437 byte 0x\(key)")
    }
}

@Test func symmetricBlocksMatchesPythonVectors() throws {
    let vectors = try loadJob005Vectors().symmetricBlocks
    #expect(vectors.count == 7)
    for (i, v) in vectors.enumerated() {
        let got = symmetricBlocks(bytesFromHex(v.inputHex))
        #expect(hexFromBytes(got.bytes) == v.outputHex, "symmetric_blocks vector \(i): bytes")
        #expect(got.footnotes == v.footnotes, "symmetric_blocks vector \(i): footnotes")
    }
}

@Test func bareLFClassifiesAsHard() throws {
    // job-003 flagged a lone 0x0A as unproven by the vector suite: it classifies as
    // `hard` (brk[0] != 0x8D at core.py:116), which is easy to get backwards. This
    // vector (job-004-vectors.md's lines_pass_extra) closes that gap.
    let vectors = try loadJob004Vectors().linesPassExtra
    #expect(vectors.count == 1)
    for (i, v) in vectors.enumerated() {
        assertLinesPassVector(v, label: "lines_pass_extra vector \(i)")
    }
}
