import Foundation
import Testing
@testable import CtrlKD

/// Equivalence proof against `Resources/job-003-vectors.json` — machine-generated by
/// the Python ctrl-kd 1.1.3 implementation. Every vector must reproduce exactly.
///
/// `Foundation` is imported here for `JSONDecoder`/`Bundle` only; the `CtrlKD` library
/// target itself stays Foundation-free.

private struct VectorFile: Decodable {
    let detect: [DetectVector]
    let linesPass: [LinesPassVector]
    let note: String

    enum CodingKeys: String, CodingKey {
        case detect
        case linesPass = "lines_pass"
        case note
    }
}

private struct DetectVector: Decodable {
    let inputHex: String
    let variant: String
    // Absent for the empty / ^Z-at-start vectors: Python's detect() returns those before
    // it computes any evidence, so there is nothing to assert for them.
    let softReturns: Int?
    let hardReturns: Int?
    let highBitBytes: Int?
    let textPct: Int?
    let symmetricBlocks1D: Int?
    let size: Int?

    enum CodingKeys: String, CodingKey {
        case inputHex = "input_hex"
        case variant
        case softReturns = "soft_returns"
        case hardReturns = "hard_returns"
        case highBitBytes = "high_bit_bytes"
        case textPct = "text_pct"
        case symmetricBlocks1D = "symmetric_blocks_1d"
        case size
    }
}

private struct LinesPassVector: Decodable {
    let inputHex: String
    let margin: Int
    let lines: [LineVector]

    enum CodingKeys: String, CodingKey {
        case inputHex = "input_hex"
        case margin
        case lines
    }
}

private struct LineVector: Decodable {
    let textHex: String
    let sep: String

    enum CodingKeys: String, CodingKey {
        case textHex = "text_hex"
        case sep
    }
}

private struct Job004VectorFile: Decodable {
    let cp437ByteToUnicodeCodepoint: [String: Int]
    let linesPassExtra: [LinesPassVector]
    let note: String

    enum CodingKeys: String, CodingKey {
        case cp437ByteToUnicodeCodepoint = "cp437_byte_to_unicode_codepoint"
        case linesPassExtra = "lines_pass_extra"
        case note
    }
}

private func loadVectors() throws -> VectorFile {
    let url = try #require(
        Bundle.module.url(forResource: "job-003-vectors", withExtension: "json"),
        "job-003-vectors.json missing from the test bundle"
    )
    return try JSONDecoder().decode(VectorFile.self, from: Data(contentsOf: url))
}

private func loadJob004Vectors() throws -> Job004VectorFile {
    let url = try #require(
        Bundle.module.url(forResource: "job-004-vectors", withExtension: "json"),
        "job-004-vectors.json missing from the test bundle"
    )
    return try JSONDecoder().decode(Job004VectorFile.self, from: Data(contentsOf: url))
}

private struct SymmetricBlocksVector: Decodable {
    let inputHex: String
    let outputHex: String
    let footnotes: [String]

    enum CodingKeys: String, CodingKey {
        case inputHex = "input_hex"
        case outputHex = "output_hex"
        case footnotes
    }
}

private struct Job005VectorFile: Decodable {
    let symmetricBlocks: [SymmetricBlocksVector]
    let note: String

    enum CodingKeys: String, CodingKey {
        case symmetricBlocks = "symmetric_blocks"
        case note
    }
}

private func loadJob005Vectors() throws -> Job005VectorFile {
    let url = try #require(
        Bundle.module.url(forResource: "job-005-vectors", withExtension: "json"),
        "job-005-vectors.json missing from the test bundle"
    )
    return try JSONDecoder().decode(Job005VectorFile.self, from: Data(contentsOf: url))
}

// MARK: - job-006 (parse_ws end-to-end Documents)

private struct SpanVector: Decodable {
    let text: String
    let styles: [String]
}

private struct BlockVector: Decodable {
    let kind: String
    let heading: Int
    /// Python serializes each line as a bare list of spans, so a line is `[[SpanVector]]`
    /// nested one deeper than it reads.
    let lines: [[SpanVector]]
}

private struct MetaVector: Decodable {
    let variant: String
    let marginEstimate: Int
    let dotCommands: [String]
    /// Hex-string keyed (`"0x07"`), matching Python's `--diagnose` formatting; converted
    /// to raw bytes for comparison against `Document.unknownCodes`.
    let unknownCodes: [String: Int]
    let columnar: Bool

    enum CodingKeys: String, CodingKey {
        case variant
        case marginEstimate = "margin_estimate"
        case dotCommands = "dot_commands"
        case unknownCodes = "unknown_codes"
        case columnar
    }
}

private struct DocumentVector: Decodable {
    let blocks: [BlockVector]
    let footnotes: [String]
    let meta: MetaVector
}

private struct ParseWSVector: Decodable {
    let inputHex: String
    let document: DocumentVector

    enum CodingKeys: String, CodingKey {
        case inputHex = "input_hex"
        case document
    }
}

private struct Job006VectorFile: Decodable {
    let parseWS: [ParseWSVector]
    let symmetricBlocksExtra: [SymmetricBlocksVector]
    let note: String

    enum CodingKeys: String, CodingKey {
        case parseWS = "parse_ws"
        case symmetricBlocksExtra = "symmetric_blocks_extra"
        case note
    }
}

private func loadJob006Vectors() throws -> Job006VectorFile {
    let url = try #require(
        Bundle.module.url(forResource: "job-006-vectors", withExtension: "json"),
        "job-006-vectors.json missing from the test bundle"
    )
    return try JSONDecoder().decode(Job006VectorFile.self, from: Data(contentsOf: url))
}

// MARK: - job-007 (parse_printstream + parse front door)

/// Printstream documents carry only `variant` and `columnar` — `parse_printstream` builds
/// its meta by hand and never runs detection or the wrap test.
private struct PrintstreamMetaVector: Decodable {
    let variant: String
    let columnar: Bool
}

private struct PrintstreamDocumentVector: Decodable {
    let blocks: [BlockVector]
    let footnotes: [String]
    let meta: PrintstreamMetaVector
}

private struct PrintstreamVector: Decodable {
    let inputHex: String
    let document: PrintstreamDocumentVector

    enum CodingKeys: String, CodingKey {
        case inputHex = "input_hex"
        case document
    }
}

private struct FrontDoorVector: Decodable {
    let inputHex: String
    let routesTo: String

    enum CodingKeys: String, CodingKey {
        case inputHex = "input_hex"
        case routesTo = "routes_to"
    }
}

private struct Job007VectorFile: Decodable {
    let parsePrintstream: [PrintstreamVector]
    let parseFrontDoor: [FrontDoorVector]
    let note: String

    enum CodingKeys: String, CodingKey {
        case parsePrintstream = "parse_printstream"
        case parseFrontDoor = "parse_front_door"
        case note
    }
}

private func loadJob007Vectors() throws -> Job007VectorFile {
    let url = try #require(
        Bundle.module.url(forResource: "job-007-vectors", withExtension: "json"),
        "job-007-vectors.json missing from the test bundle"
    )
    return try JSONDecoder().decode(Job007VectorFile.self, from: Data(contentsOf: url))
}

/// Shared block/line/span/style comparison, used by both the parse_ws and
/// parse_printstream vector suites.
private func assertBlocks(_ got: [Block], _ want: [BlockVector], label: String) {
    #expect(got.count == want.count, "\(label): block count")
    for (b, wantBlock) in want.enumerated() where b < got.count {
        let gotBlock = got[b]
        #expect(gotBlock.kind.rawValue == wantBlock.kind, "\(label) block \(b): kind")
        #expect(gotBlock.heading == wantBlock.heading, "\(label) block \(b): heading")
        #expect(gotBlock.lines.count == wantBlock.lines.count, "\(label) block \(b): line count")
        for (l, wantLine) in wantBlock.lines.enumerated() where l < gotBlock.lines.count {
            let gotSpans = gotBlock.lines[l].spans
            #expect(gotSpans.count == wantLine.count, "\(label) block \(b) line \(l): span count")
            for (s, wantSpan) in wantLine.enumerated() where s < gotSpans.count {
                #expect(gotSpans[s].text == wantSpan.text,
                        "\(label) block \(b) line \(l) span \(s): text")
                #expect(styleCodes(gotSpans[s].styles) == wantSpan.styles.sorted(),
                        "\(label) block \(b) line \(l) span \(s): styles")
            }
        }
    }
}

/// `Style` -> the Python style-code strings the vectors use, sorted for comparison.
/// Lives in the test target: the codes are the Python wire format, and nothing in
/// `Sources/` needs them until an emitter does.
private func styleCodes(_ style: Style) -> [String] {
    var codes: [String] = []
    if style.contains(.bold) { codes.append("b") }
    if style.contains(.italic) { codes.append("i") }
    if style.contains(.underline) { codes.append("u") }
    if style.contains(.sup) { codes.append("sup") }
    if style.contains(.sub) { codes.append("sub") }
    if style.contains(.strike) { codes.append("strike") }
    if style.contains(.fnref) { codes.append("fnref") }
    return codes.sorted()
}

private func bytesFromHex(_ hex: String) -> [UInt8] {
    let chars = Array(hex)
    precondition(chars.count % 2 == 0, "hex string must have an even length")
    var out: [UInt8] = []
    out.reserveCapacity(chars.count / 2)
    for i in stride(from: 0, to: chars.count, by: 2) {
        out.append(UInt8(String(chars[i...(i + 1)]), radix: 16)!)
    }
    return out
}

private func hexFromBytes(_ bytes: [UInt8]) -> String {
    bytes.map { String(format: "%02x", $0) }.joined()
}

@Test func detectMatchesPythonVectors() throws {
    let vectors = try loadVectors().detect
    #expect(vectors.count == 7)
    for (i, v) in vectors.enumerated() {
        let got = detect(bytesFromHex(v.inputHex))
        #expect(got.variant.rawValue == v.variant, "detect vector \(i): variant")
        if let expected = v.softReturns {
            #expect(got.softReturns == expected, "detect vector \(i): soft_returns")
        }
        if let expected = v.hardReturns {
            #expect(got.hardReturns == expected, "detect vector \(i): hard_returns")
        }
        if let expected = v.highBitBytes {
            #expect(got.highBitBytes == expected, "detect vector \(i): high_bit_bytes")
        }
        if let expected = v.textPct {
            #expect(got.textPct == expected, "detect vector \(i): text_pct")
        }
        if let expected = v.symmetricBlocks1D {
            #expect(got.symmetricBlocks1D == expected, "detect vector \(i): symmetric_blocks_1d")
        }
        if let expected = v.size {
            #expect(got.size == expected, "detect vector \(i): size")
        }
    }
}

private func assertLinesPassVector(_ v: LinesPassVector, label: String) {
    let got = linesPass(bytesFromHex(v.inputHex))
    #expect(got.margin == v.margin, "\(label): margin")
    #expect(got.lines.count == v.lines.count, "\(label): line count")
    for (j, expected) in v.lines.enumerated() where j < got.lines.count {
        let line = got.lines[j]
        #expect(line.separator.rawValue == expected.sep, "\(label) line \(j): sep")
        #expect(hexFromBytes(line.text) == expected.textHex, "\(label) line \(j): text")
    }
}

@Test func linesPassMatchesPythonVectors() throws {
    let vectors = try loadVectors().linesPass
    #expect(vectors.count == 8)
    for (i, v) in vectors.enumerated() {
        assertLinesPassVector(v, label: "lines_pass vector \(i)")
    }
}

@Test func cp437TableMatchesPythonVectors() throws {
    let table = try loadJob004Vectors().cp437ByteToUnicodeCodepoint
    #expect(table.count == 256)
    for byte in 0...255 {
        let key = String(format: "%02x", byte)
        let expected = try #require(table[key], "cp437 vector missing byte 0x\(key)")
        let decoded = decodeCP437([UInt8(byte)])
        let scalar = try #require(decoded.unicodeScalars.first, "byte 0x\(key) decoded to empty string")
        #expect(Int(scalar.value) == expected, "cp437 byte 0x\(key)")
    }
}

@Test func symmetricBlocksMatchesPythonVectors() throws {
    let vectors = try loadJob005Vectors().symmetricBlocks
    #expect(vectors.count == 7)
    for (i, v) in vectors.enumerated() {
        let got = symmetricBlocks(bytesFromHex(v.inputHex))
        #expect(hexFromBytes(got.bytes) == v.outputHex, "symmetric_blocks vector \(i): bytes")
        #expect(got.footnotes == v.footnotes, "symmetric_blocks vector \(i): footnotes")
    }
}

@Test func parseWSMatchesPythonVectors() throws {
    let vectors = try loadJob006Vectors().parseWS
    #expect(vectors.count == 7)
    for (i, v) in vectors.enumerated() {
        let doc = parseWS(bytesFromHex(v.inputHex))
        let want = v.document
        let label = "parse_ws vector \(i)"

        // meta
        #expect(doc.detection?.variant.rawValue == want.meta.variant, "\(label): variant")
        #expect(doc.marginEstimate == want.meta.marginEstimate, "\(label): margin_estimate")
        #expect(doc.dotCommands == want.meta.dotCommands, "\(label): dot_commands")
        #expect(doc.columnar == want.meta.columnar, "\(label): columnar")
        var wantUnknown: [UInt8: Int] = [:]
        for (key, count) in want.meta.unknownCodes {
            let hex = key.hasPrefix("0x") ? String(key.dropFirst(2)) : key
            wantUnknown[UInt8(hex, radix: 16)!] = count
        }
        #expect(doc.unknownCodes == wantUnknown, "\(label): unknown_codes")

        // footnotes, compared as the joined span text Python serializes
        let gotFootnotes = doc.footnotes.map { $0.map(\.text).joined() }
        #expect(gotFootnotes == want.footnotes, "\(label): footnotes")

        // blocks / lines / spans / styles
        assertBlocks(doc.blocks, want.blocks, label: label)
    }
}

@Test func parsePrintstreamMatchesPythonVectors() throws {
    let vectors = try loadJob007Vectors().parsePrintstream
    #expect(vectors.count == 6)
    for (i, v) in vectors.enumerated() {
        let doc = parsePrintstream(bytesFromHex(v.inputHex))
        let want = v.document
        let label = "parse_printstream vector \(i)"

        #expect(doc.detection?.variant.rawValue == want.meta.variant, "\(label): variant")
        #expect(doc.columnar == want.meta.columnar, "\(label): columnar")
        // Never runs the wrap test, so there is no margin to report.
        #expect(doc.marginEstimate == nil, "\(label): marginEstimate should be nil")
        #expect(doc.footnotes.map { $0.map(\.text).joined() } == want.footnotes,
                "\(label): footnotes")
        assertBlocks(doc.blocks, want.blocks, label: label)
    }
}

@Test func parseFrontDoorRoutesPythonVectors() throws {
    let vectors = try loadJob007Vectors().parseFrontDoor
    #expect(vectors.count == 2)
    for (i, v) in vectors.enumerated() {
        let data = bytesFromHex(v.inputHex)
        let label = "parse_front_door vector \(i)"
        if v.routesTo == "REFUSES" {
            #expect(throws: ParseError.self, "\(label): expected refusal") {
                _ = try parse(data)
            }
        } else {
            let doc = try parse(data)
            #expect(doc.detection?.variant.rawValue == v.routesTo, "\(label): routed variant")
        }
    }
}

@Test func symmetricBlocksExtraVectors() throws {
    // The NBSP note-strip case, folded into the canonical vector set per job-005's
    // request — this replaces the hand-authored fixture that lived in
    // SymmetricBlocksTests.swift.
    let vectors = try loadJob006Vectors().symmetricBlocksExtra
    #expect(vectors.count == 1)
    for (i, v) in vectors.enumerated() {
        let got = symmetricBlocks(bytesFromHex(v.inputHex))
        #expect(hexFromBytes(got.bytes) == v.outputHex, "symmetric_blocks_extra \(i): bytes")
        #expect(got.footnotes == v.footnotes, "symmetric_blocks_extra \(i): footnotes")
    }
}

@Test func bareLFClassifiesAsHard() throws {
    // job-003 flagged a lone 0x0A as unproven by the vector suite: it classifies as
    // `hard` (brk[0] != 0x8D at core.py:116), which is easy to get backwards. This
    // vector (job-004-vectors.md's lines_pass_extra) closes that gap.
    let vectors = try loadJob004Vectors().linesPassExtra
    #expect(vectors.count == 1)
    for (i, v) in vectors.enumerated() {
        assertLinesPassVector(v, label: "lines_pass_extra vector \(i)")
    }
}
