/// The typestyle-number -> typeface-name table, verbatim from MicroPro's File Format for
/// WordStar Release 7.0 (WSFORMAT.TXT, "Typestyles are defined by a word..." section;
/// public copy: sfwriter.com/wsformat.txt). 245 entries, numbers 0-244; parenthetical
/// alternate names are the spec's own text, kept verbatim per the pass-through rule (the
/// consumer decides what to do with a name -- this table never picks a font).
///
/// The typestyle NUMBER is the low 9 bits of the font block's typestyle word, which is
/// what `FontChange.typestyleNumber` already exposes; `FontChange.typestyleName` is this
/// table's answer for it, `nil` for a number the table does not carry.
///
/// A CONTIGUOUS ARRAY, not a dictionary: the keys are exactly 0...244 with no gaps, so an
/// array indexed by the number is the same lookup with none of the hashing -- and the
/// bounds check IS the "does the table carry this number" test.
let typestyleNames: [String] = [
    "LinePrinter",
    "Pica",
    "Elite",
    "Courier",
    "Helv (also Helvetica, CG Triumvirate, and Swiss)",
    "Tms Rmn (also CG Times, Times Roman and Dutch)",
    "Gothic (see also 130 Letter Gothic)",
    "Script",
    "Prestige (see also 48 Prestige Elite)",
    "Caslon",
    "Orator",
    "Presentations",
    "Helv Cond. (also Swiss Condensed)",
    "Serifa",
    "Blippo",
    "Windsor",
    "Century (also see #23)",
    "ZapfHumanist",
    "Garamond",
    "Cooper",
    "Coronet",
    "Broadway",
    "Bodoni",
    "Cntry Schlbk (also see #16)",
    "Univ. Roman",
    "Helv Outline",
    "Peignot (also Exotic)",
    "Clarendon",
    "Stick",
    "HP-GL Drafting",
    "HP-GL Spline",
    "Times",
    "HPLJ Soft Font",
    "Borders",
    "Uncle Sam Open",
    "Raphael",
    "Uncial",
    "Manhattan",
    "Dom Casual",
    "Old English",
    "Trium Condensed",
    "Trium UltraComp",
    "Trade ExtraCond",
    "American Classic (also Amerigo)",
    "Globe Gothic Outline",
    "UniversCondensed (also Zurich Condensed)",
    "Univers (also Zurich)",
    "TmsRmnCond (Oki Laserline 6)",
    "PrstElite (see also 8 Prestige)",
    "Optima",
    "Aachen (Postscript)",
    "AmTypewriter",
    "Avant Garde",
    "Benguiat",
    "Brush Script",
    "Carta",
    "Centennial",
    "Cheltenham",
    "FranklinGothic",
    "FrstyleScrpt",
    "FrizQuadrata",
    "Futura",
    "Galliard",
    "Glypha",
    "Goudy",
    "Hobo",
    "LubalinGraph",
    "Lucida",
    "LucidaMath",
    "Machine",
    "Melior (also Zapf Elliptical)",
    "NewBaskrvlle (also Baskerville)",
    "NewCntSchlbk",
    "News Gothic (also Trade Gothic)",
    "Palatino (also Zapf Calligraphic)",
    "Park Avenue",
    "Revue",
    "Sonata",
    "Stencil",
    "Souvenir",
    "TrmpMedievel (also Activa)",
    "ZapfChancery",
    "ZapfDingbats",
    "Stone",
    "CntryOldStyle",
    "Corona",
    "GoudyOldStyle",
    "Excelsior",
    "FuturaCondensed",
    "HelvCompressed",
    "HelvExtraCompressed",
    "Helv Narrow",
    "HelvUltraCompressed",
    "KorinnaKursiv",
    "Lucida Sans",
    "Memphis",
    "Stone Informal",
    "Stone Sans",
    "Stone Serif",
    "Postscript",
    "NPS Utility",
    "NPS Draft",
    "NPS Corr",
    "NPS SansSer Qual",
    "NPS Serif Qual",
    "PS Utility",
    "PS Draft",
    "PS Corr",
    "PS SansSer Qual",
    "PS Serif Qual",
    "Download",
    "NPS ECS Qual (daisy wheel)",
    "PS Plastic (daisy wheel)",
    "PS Metal (daisy wheel)",
    "CloisterBlack",
    "Gill Sans (also Hammersmith)",
    "Rockwell (also Slate)",
    "Tiffany (ITC)",
    "Clearface",
    "Amelia",
    "HandelGothic",
    "OratorSC (Star et al)",
    "Outline (Toshiba)",
    "Bookman Light (Canon)",
    "Humanist (Canon)",
    "Swiss Narrow (Canon)",
    "ZapfCalligraphic (Canon)",
    "Spreadsheet (Quadlaser)",
    "Broughm (Brother printers)",
    "Anelia (Brother printers)",
    "LtrGothic (as defined by Brother)",
    "Boldface (Boldface PS)",
    "High Density (NEC)",
    "High Speed (NEC)",
    "Super Focus (NEC P2200)",
    "Swiss Outline (Cordata)",
    "Swiss Display (Cordata)",
    "Momento Outline (Cordata)",
    "Courier Italic (TI 855)",
    "Text Light (Cordata)",
    "Momento Heavy (Cordata)",
    "BarCode",
    "EAN/UPC",
    "Math-7 (HPLJ)",
    "Math-8 (HPLJ)",
    "Swiss",
    "Dutch",
    "Trend (Nissho)",
    "Holsatia (Qume Laser)",
    "Serif (IBM Pageprinter)",
    "Bandit (Cordata)",
    "Bookman (Cordata)",
    "Casual (Cordata)",
    "Dot (Cordata)",
    "EDP (Epson GQ3500)",
    "ExtGraphics (Epson GQ3500)",
    "Garland (Canon Laser)",
    "PC Line",
    "HP Line",
    "Hamilton (QMS)",
    "Korinna (Cordata)",
    "LineDrw (QMS)",
    "Modern",
    "Momento (Cordata)",
    "MX (Cordata)",
    "PC (Cordata)",
    "PI",
    "Profile (Quadlaser)",
    "Q-Fmt (QMS)",
    "Rule (Cordata)",
    "SB (Cordata)",
    "Taylor (Cordata)",
    "Text (Cordata)",
    "APL",
    "Artisan",
    "Triumvirate",
    "Chart",
    "Classic",
    "Data",
    "Document",
    "Emperor",
    "Essay",
    "Forms",
    "Facet",
    "Micro (also Microstyle, Eurostyle)",
    "OCR-A",
    "OCR-B",
    "Apollo (Blaser)",
    "Math",
    "Scientific",
    "Sonoran (IBM Pageprinter)",
    "Square 3",
    "Symbol",
    "Tempora",
    "Title",
    "Titan",
    "Theme",
    "TaxLineDraw",
    "Vintage",
    "XCP",
    "Eletto (Olivetti)",
    "Est Elite (Olivetti)",
    "Idea (Olivetti)",
    "Italico (Olivetti)",
    "Kent (Olivetti)",
    "Mikron (Olivetti)",
    "Notizia (Olivetti)",
    "Roma (Olivetti)",
    "Presentor (Olivetti)",
    "Victoria (Olivetti)",
    "Draft Italic (Olivetti)",
    "PS Capita (Olivetti)",
    "Qual Italic (Olivetti)",
    "Antique Olive (also Provence)",
    "Bauhaus (ITC)",
    "Eras (ITC)",
    "Mincho",
    "SerifGothic (ITC)",
    "Signet Roundhand",
    "Souvenir Gothic",
    "Stymie (ATF)",
    "Bernhard Modern",
    "Grand Ronde Script",
    "Ondine (also Mermaid)",
    "PT Barnum",
    "Kaufmann",
    "Bolt (ITC)",
    "AntOliveCompact (also Provence Compact)",
    "Garth Graphic",
    "Ronda (ITC)",
    "EngShcreibschrift",
    "Flash",
    "Gothic Outline (URW)",
    "Akzidenz-Grotesk",
    "TD Logos",
    "Shannon",
    "Oberon",
    "Callisto",
    "Charter",
    "Plantin",
    "Helvetica Black (PS)",
    "Helvetica Light (PS)",
    "Arnold Bocklin (PS)",
    "Fette Fraktur (PS)",
    "Greek (PS (Universal Greek))",
]
