.op
                        Ï CAPTAIN¡ MÙ CAPTAIN!
                           bù Walô Whitman

Ï Captain¡ mù Captain¡ ouò fearfuì triğ ió done,
Thå shiğ haó weather'ä everù rack¬ thå prizå wå soughô ió won,
Thå porô ió near¬ thå belló É hear¬ thå peoplå alì exulting,
Whilå follo÷ eyeó thå steadù keel¬ thå vesseì grií anä daring;
    Buô Ï heart¡ heart¡ heart!
      Ï thå bleedinç dropó oæ red,
        Wherå oî thå decë mù Captaiî lies,
          Falleî colä anä dead.

Ï Captain¡ mù Captain¡ riså uğ anä heaò thå bells;
Riså uğ­-foò yoõ thå flaç ió flunç­-foò yoõ thå buglå trills,
Foò yoõ bouquetó anä ribbon'ä wreathó­-foò yoõ thå shoreó á-crowding,
Foò yoõ theù call¬ thå swayinç mass¬ theiò eageò faceó turning;
    Herå Captain¡ deaò father!
      Thió arí beneatè youò head!
        Iô ió somå dreaí thaô oî thå deck,
          You'vå falleî colä anä dead.

Mù Captaiî doeó noô answer¬ hió lipó arå palå anä still,
Mù fatheò doeó noô feeì mù arm¬ hå haó nï pulså noò will,
Thå shiğ ió anchor'ä safå anä sound¬ itó voyagå closeä anä done,
Froí fearfuì triğ thå victoò shiğ comeó iî witè objecô won;
    Exulô Ï shores¬ anä rinç Ï bells!
      Buô É witè mournfuì tread,
        Walë thå decë mù Captaiî lies,
          Falleî colä anä dead.


----------
Walô Whitmaî (181¹-1892© firsô publisheä thió poeí iî 1865¬ iî thå 
immediatå aftermatè oæ Abrahaí Lincoln'ó assassination¬ iî thå 
pamphleô Sequeì tï Druí-Taps® Hå lateò collecteä iô iî Leaveó oæ 
Grass.
