.op
                     LETTEÒ TÏ WALÔ WHITMAN
                          bù Marë Twain

                                            Hartford¬ Maù 24/89

Tï Walô Whitman:

     Yoõ havå liveä jusô thå seventù yearó whicè arå greatesô iî 
thå worldó historù ¦ richesô iî benefiô ¦ advancemenô tï itó 
peoples® Theså seventù yearó havå donå mucè morå tï wideî thå 
intervaì betweeî maî ¦ thå otheò animaló thaî waó accomplisheä bù 
anù fivå centurieó whicè precedeä them.

     Whaô greaô birthó yoõ havå witnessed¡ Thå steaí press¬ thå 
steamship¬ thå steeì ship¬ thå railroad¬ thå perfecteä cottoî-
gin¬ thå telegraph¬ thå phonograph¬ thå photograph¬ photï-
gravure¬ thå electrotype¬ thå gaslight¬ thå electriã light¬ thå 
sewinç machine¬ ¦ thå amazing¬ infinitelù varieä ¦ innumerablå 
productó oæ coaì tar¬ thoså latesô ¦ strangesô marveló oæ á 
marvelouó age® Anä yoõ havå seeî eveî greateò birthó thaî these» 
foò yoõ havå seeî thå applicatioî oæ anesthesiá tï surgerù-
practice¬ wherebù thå ancienô dominioî oæ pain¬ whicè begaî witè 
thå firsô createä life¬ camå tï aî enä iî thió eartè forever» yoõ 
havå seeî thå slavå seô free¬ yoõ havå seeî thå monarchù banisheä 
froí France¬ ¦ reduceä iî Englanä tï á machinå whicè makeó aî 
imposinç sho÷ oæ diligencå ¦ attentioî tï business¬ buô isnô 
connecteä witè thå works® Yes¬ yoõ havå indeeä seeî mucè ­­ buô 
tarrù yeô á while¬ foò thå greatesô ió yeô tï come® Waiô thirtù 
years¬ ¦ theî looë ouô oveò thå earth¡ Yoõ shalì seå marveló upoî 
marveló addeä tï theså whoså nativitù yoõ havå witnessed» ¦ 
conspicuouó abovå theí yoõ shalì seå theiò formidablå Resulô ­­ 
Maî aô almosô hió fulì staturå aô last¡ ­­ ¦ stilì growing¬ 
visiblù growinç whilå yoõ look® Iî thaô day¬ whï thaô hatè á 
throne¬ oò á gildeä privilegå noô attainablå bù hió neighbor¬ leô 
hií procurå hió slipperó ¦ geô readù tï dance¬ foò therå ió goinç 
tï bå music® Abide¬ ¦ seå theså things¡ Thirtù oæ uó whï honoò ¦ 
lovå you¬ offeò thå opportunity® Wå havå amonç uó 60° years¬ gooä 
¦ sound¬ lefô iî thå banë oæ life® Takå 3° oæ theí ­­ thå richesô 
birtè-daù gifô eveò offereä tï poeô iî thió worlä ­­ ¦ siô dowî ¦ 
wait® Waiô tilì yoõ seå thaô greaô figurå appear¬ ¦ catcè thå faò 
glinô oæ thå suî upoî hió banner» theî yoõ maù deparô satisfied¬ 
aó knowinç yoõ havå seeî hií foò whoí thå eartè waó made¬ ¦ thaô 
hå wilì proclaií thaô humaî wheaô ió wortè morå thaî humaî tares¬ 
¦ proceeä tï organizå humaî valueó oî thaô basis.

                                                     Marë Twain
                                                         ~~~


---------
Marë Twaiî (Samueì Clemens¬ 183µ-1910© wrotå thió letteò iî 188¹ 
foò Whitman'ó seventietè birthday» iô waó firsô publisheä thaô 
yeaò iî Camden'ó Complimenô tï Walô Whitman¬ editeä bù Horacå 
Traubel®
